import type { ShortcutScheme } from './shortcut-types.js';

// ==================== 预设方案 ====================

/** Premiere 风格方案 */
export const PREMIERE_SCHEME: ShortcutScheme = {
  id: 'premiere',
  name: 'Premiere Pro 风格',
  description: 'Adobe Premiere Pro 快捷键方案',
  isDefault: true,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  shortcuts: [
    {
      id: 'play-pause',
      action: 'play-pause',
      keys: ['Space'],
      modifiers: [],
      label: '播放/暂停',
      description: '切换播放状态',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'stop',
      action: 'stop',
      keys: ['Escape'],
      modifiers: [],
      label: '停止',
      description: '停止播放',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'next-frame',
      action: 'next-frame',
      keys: ['ArrowRight'],
      modifiers: [],
      label: '下一帧',
      description: '前进一帧',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'previous-frame',
      action: 'previous-frame',
      keys: ['ArrowLeft'],
      modifiers: [],
      label: '上一帧',
      description: '后退一帧',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'go-to-start',
      action: 'go-to-start',
      keys: ['Home'],
      modifiers: [],
      label: '跳到开头',
      description: '跳转到时间线开头',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'go-to-end',
      action: 'go-to-end',
      keys: ['End'],
      modifiers: [],
      label: '跳到结尾',
      description: '跳转到时间线结尾',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'split-clip',
      action: 'split-clip',
      keys: ['c'],
      modifiers: ['ctrl'],
      label: '分割片段',
      description: '在播放头位置分割片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'delete-clip',
      action: 'delete-clip',
      keys: ['Delete'],
      modifiers: [],
      label: '删除片段',
      description: '删除选中的片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'undo',
      action: 'undo',
      keys: ['z'],
      modifiers: ['ctrl'],
      label: '撤销',
      description: '撤销上一步操作',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'redo',
      action: 'redo',
      keys: ['z'],
      modifiers: ['ctrl', 'shift'],
      label: '重做',
      description: '重做上一步操作',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'copy',
      action: 'copy',
      keys: ['c'],
      modifiers: ['ctrl'],
      label: '复制',
      description: '复制选中内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'paste',
      action: 'paste',
      keys: ['v'],
      modifiers: ['ctrl'],
      label: '粘贴',
      description: '粘贴内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'cut',
      action: 'cut',
      keys: ['x'],
      modifiers: ['ctrl'],
      label: '剪切',
      description: '剪切选中内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'select-all',
      action: 'select-all',
      keys: ['a'],
      modifiers: ['ctrl'],
      label: '全选',
      description: '选择所有内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'zoom-in',
      action: 'zoom-in',
      keys: ['='],
      modifiers: ['ctrl'],
      label: '放大',
      description: '放大时间线',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'zoom-out',
      action: 'zoom-out',
      keys: ['-'],
      modifiers: ['ctrl'],
      label: '缩小',
      description: '缩小时间线',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'zoom-fit',
      action: 'zoom-fit',
      keys: ['0'],
      modifiers: ['ctrl'],
      label: '适应窗口',
      description: '时间线适应窗口大小',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'toggle-zen-mode',
      action: 'toggle-zen-mode',
      keys: ['F11'],
      modifiers: [],
      label: 'Zen 模式',
      description: '切换 Zen 专注模式',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'toggle-fullscreen',
      action: 'toggle-fullscreen',
      keys: ['F'],
      modifiers: ['ctrl'],
      label: '全屏',
      description: '切换全屏模式',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'export',
      action: 'export',
      keys: ['e'],
      modifiers: ['ctrl'],
      label: '导出',
      description: '导出项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'save',
      action: 'save',
      keys: ['s'],
      modifiers: ['ctrl'],
      label: '保存',
      description: '保存项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'save-as',
      action: 'save-as',
      keys: ['s'],
      modifiers: ['ctrl', 'shift'],
      label: '另存为',
      description: '项目另存为',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'open',
      action: 'open',
      keys: ['o'],
      modifiers: ['ctrl'],
      label: '打开',
      description: '打开项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'new-project',
      action: 'new-project',
      keys: ['n'],
      modifiers: ['ctrl'],
      label: '新建项目',
      description: '创建新项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'import-media',
      action: 'import-media',
      keys: ['i'],
      modifiers: ['ctrl'],
      label: '导入媒体',
      description: '导入媒体文件',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'mark-in',
      action: 'mark-in',
      keys: ['I'],
      modifiers: [],
      label: '入点',
      description: '设置入点',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'mark-out',
      action: 'mark-out',
      keys: ['O'],
      modifiers: [],
      label: '出点',
      description: '设置出点',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'clear-marks',
      action: 'clear-marks',
      keys: ['D'],
      modifiers: ['ctrl'],
      label: '清除标记',
      description: '清除入点和出点',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'add-marker',
      action: 'add-marker',
      keys: ['M'],
      modifiers: [],
      label: '添加标记',
      description: '在当前位置添加标记',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'toggle-mute',
      action: 'toggle-mute',
      keys: ['M'],
      modifiers: ['ctrl'],
      label: '静音',
      description: '切换静音状态',
      category: '音频',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'volume-up',
      action: 'volume-up',
      keys: [']'],
      modifiers: ['ctrl'],
      label: '增加音量',
      description: '增加音量',
      category: '音频',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'volume-down',
      action: 'volume-down',
      keys: ['['],
      modifiers: ['ctrl'],
      label: '降低音量',
      description: '降低音量',
      category: '音频',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'toggle-loop',
      action: 'toggle-loop',
      keys: ['L'],
      modifiers: ['ctrl'],
      label: '循环',
      description: '切换循环播放',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'toggle-snapping',
      action: 'toggle-snapping',
      keys: ['S'],
      modifiers: ['ctrl'],
      label: '吸附',
      description: '切换吸附功能',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'nudge-left',
      action: 'nudge-left',
      keys: [','],
      modifiers: ['ctrl'],
      label: '左微调',
      description: '向左微调片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'nudge-right',
      action: 'nudge-right',
      keys: ['.'],
      modifiers: ['ctrl'],
      label: '右微调',
      description: '向右微调片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
  ],
};

/** Final Cut Pro 风格方案 */
export const FINAL_CUT_SCHEME: ShortcutScheme = {
  id: 'final-cut',
  name: 'Final Cut Pro 风格',
  description: 'Apple Final Cut Pro 快捷键方案',
  isDefault: false,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  shortcuts: [
    {
      id: 'play-pause',
      action: 'play-pause',
      keys: ['Space'],
      modifiers: [],
      label: '播放/暂停',
      description: '切换播放状态',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'stop',
      action: 'stop',
      keys: ['Escape'],
      modifiers: [],
      label: '停止',
      description: '停止播放',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'next-frame',
      action: 'next-frame',
      keys: ['ArrowRight'],
      modifiers: [],
      label: '下一帧',
      description: '前进一帧',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'previous-frame',
      action: 'previous-frame',
      keys: ['ArrowLeft'],
      modifiers: [],
      label: '上一帧',
      description: '后退一帧',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'go-to-start',
      action: 'go-to-start',
      keys: ['Home'],
      modifiers: [],
      label: '跳到开头',
      description: '跳转到时间线开头',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'go-to-end',
      action: 'go-to-end',
      keys: ['End'],
      modifiers: [],
      label: '跳到结尾',
      description: '跳转到时间线结尾',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'split-clip',
      action: 'split-clip',
      keys: ['B'],
      modifiers: [],
      label: '分割片段',
      description: '在播放头位置分割片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'delete-clip',
      action: 'delete-clip',
      keys: ['Delete'],
      modifiers: [],
      label: '删除片段',
      description: '删除选中的片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'undo',
      action: 'undo',
      keys: ['z'],
      modifiers: ['meta'],
      label: '撤销',
      description: '撤销上一步操作',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'redo',
      action: 'redo',
      keys: ['z'],
      modifiers: ['meta', 'shift'],
      label: '重做',
      description: '重做上一步操作',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'copy',
      action: 'copy',
      keys: ['c'],
      modifiers: ['meta'],
      label: '复制',
      description: '复制选中内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'paste',
      action: 'paste',
      keys: ['v'],
      modifiers: ['meta'],
      label: '粘贴',
      description: '粘贴内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'cut',
      action: 'cut',
      keys: ['x'],
      modifiers: ['meta'],
      label: '剪切',
      description: '剪切选中内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'select-all',
      action: 'select-all',
      keys: ['a'],
      modifiers: ['meta'],
      label: '全选',
      description: '选择所有内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'zoom-in',
      action: 'zoom-in',
      keys: ['='],
      modifiers: ['meta'],
      label: '放大',
      description: '放大时间线',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'zoom-out',
      action: 'zoom-out',
      keys: ['-'],
      modifiers: ['meta'],
      label: '缩小',
      description: '缩小时间线',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'zoom-fit',
      action: 'zoom-fit',
      keys: ['0'],
      modifiers: ['meta'],
      label: '适应窗口',
      description: '时间线适应窗口大小',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'toggle-zen-mode',
      action: 'toggle-zen-mode',
      keys: ['F11'],
      modifiers: [],
      label: 'Zen 模式',
      description: '切换 Zen 专注模式',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'toggle-fullscreen',
      action: 'toggle-fullscreen',
      keys: ['F'],
      modifiers: ['meta'],
      label: '全屏',
      description: '切换全屏模式',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'export',
      action: 'export',
      keys: ['e'],
      modifiers: ['meta'],
      label: '导出',
      description: '导出项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'save',
      action: 'save',
      keys: ['s'],
      modifiers: ['meta'],
      label: '保存',
      description: '保存项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'save-as',
      action: 'save-as',
      keys: ['s'],
      modifiers: ['meta', 'shift'],
      label: '另存为',
      description: '项目另存为',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'open',
      action: 'open',
      keys: ['o'],
      modifiers: ['meta'],
      label: '打开',
      description: '打开项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'new-project',
      action: 'new-project',
      keys: ['n'],
      modifiers: ['meta'],
      label: '新建项目',
      description: '创建新项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'import-media',
      action: 'import-media',
      keys: ['i'],
      modifiers: ['meta'],
      label: '导入媒体',
      description: '导入媒体文件',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'mark-in',
      action: 'mark-in',
      keys: ['I'],
      modifiers: [],
      label: '入点',
      description: '设置入点',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'mark-out',
      action: 'mark-out',
      keys: ['O'],
      modifiers: [],
      label: '出点',
      description: '设置出点',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'clear-marks',
      action: 'clear-marks',
      keys: ['D'],
      modifiers: ['meta'],
      label: '清除标记',
      description: '清除入点和出点',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'add-marker',
      action: 'add-marker',
      keys: ['M'],
      modifiers: [],
      label: '添加标记',
      description: '在当前位置添加标记',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'toggle-mute',
      action: 'toggle-mute',
      keys: ['M'],
      modifiers: ['meta'],
      label: '静音',
      description: '切换静音状态',
      category: '音频',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'volume-up',
      action: 'volume-up',
      keys: [']'],
      modifiers: ['meta'],
      label: '增加音量',
      description: '增加音量',
      category: '音频',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'volume-down',
      action: 'volume-down',
      keys: ['['],
      modifiers: ['meta'],
      label: '降低音量',
      description: '降低音量',
      category: '音频',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'toggle-loop',
      action: 'toggle-loop',
      keys: ['L'],
      modifiers: ['meta'],
      label: '循环',
      description: '切换循环播放',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'toggle-snapping',
      action: 'toggle-snapping',
      keys: ['N'],
      modifiers: ['meta'],
      label: '吸附',
      description: '切换吸附功能',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'nudge-left',
      action: 'nudge-left',
      keys: [','],
      modifiers: ['meta'],
      label: '左微调',
      description: '向左微调片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'nudge-right',
      action: 'nudge-right',
      keys: ['.'],
      modifiers: ['meta'],
      label: '右微调',
      description: '向右微调片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
  ],
};

/** DaVinci Resolve 风格方案 */
export const DAVINCI_RESOLVE_SCHEME: ShortcutScheme = {
  id: 'davinci-resolve',
  name: 'DaVinci Resolve 风格',
  description: 'Blackmagic DaVinci Resolve 快捷键方案',
  isDefault: false,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  shortcuts: [
    {
      id: 'play-pause',
      action: 'play-pause',
      keys: ['Space'],
      modifiers: [],
      label: '播放/暂停',
      description: '切换播放状态',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'stop',
      action: 'stop',
      keys: ['Escape'],
      modifiers: [],
      label: '停止',
      description: '停止播放',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'next-frame',
      action: 'next-frame',
      keys: ['ArrowRight'],
      modifiers: [],
      label: '下一帧',
      description: '前进一帧',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'previous-frame',
      action: 'previous-frame',
      keys: ['ArrowLeft'],
      modifiers: [],
      label: '上一帧',
      description: '后退一帧',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'go-to-start',
      action: 'go-to-start',
      keys: ['Home'],
      modifiers: [],
      label: '跳到开头',
      description: '跳转到时间线开头',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'go-to-end',
      action: 'go-to-end',
      keys: ['End'],
      modifiers: [],
      label: '跳到结尾',
      description: '跳转到时间线结尾',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'split-clip',
      action: 'split-clip',
      keys: ['B'],
      modifiers: ['ctrl'],
      label: '分割片段',
      description: '在播放头位置分割片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'delete-clip',
      action: 'delete-clip',
      keys: ['Delete'],
      modifiers: [],
      label: '删除片段',
      description: '删除选中的片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'undo',
      action: 'undo',
      keys: ['z'],
      modifiers: ['ctrl'],
      label: '撤销',
      description: '撤销上一步操作',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'redo',
      action: 'redo',
      keys: ['z'],
      modifiers: ['ctrl', 'shift'],
      label: '重做',
      description: '重做上一步操作',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'copy',
      action: 'copy',
      keys: ['c'],
      modifiers: ['ctrl'],
      label: '复制',
      description: '复制选中内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'paste',
      action: 'paste',
      keys: ['v'],
      modifiers: ['ctrl'],
      label: '粘贴',
      description: '粘贴内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'cut',
      action: 'cut',
      keys: ['x'],
      modifiers: ['ctrl'],
      label: '剪切',
      description: '剪切选中内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'select-all',
      action: 'select-all',
      keys: ['a'],
      modifiers: ['ctrl'],
      label: '全选',
      description: '选择所有内容',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'zoom-in',
      action: 'zoom-in',
      keys: ['='],
      modifiers: ['ctrl'],
      label: '放大',
      description: '放大时间线',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'zoom-out',
      action: 'zoom-out',
      keys: ['-'],
      modifiers: ['ctrl'],
      label: '缩小',
      description: '缩小时间线',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'zoom-fit',
      action: 'zoom-fit',
      keys: ['0'],
      modifiers: ['ctrl'],
      label: '适应窗口',
      description: '时间线适应窗口大小',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'toggle-zen-mode',
      action: 'toggle-zen-mode',
      keys: ['F11'],
      modifiers: [],
      label: 'Zen 模式',
      description: '切换 Zen 专注模式',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'toggle-fullscreen',
      action: 'toggle-fullscreen',
      keys: ['F'],
      modifiers: ['ctrl'],
      label: '全屏',
      description: '切换全屏模式',
      category: '视图',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'export',
      action: 'export',
      keys: ['e'],
      modifiers: ['ctrl'],
      label: '导出',
      description: '导出项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'save',
      action: 'save',
      keys: ['s'],
      modifiers: ['ctrl'],
      label: '保存',
      description: '保存项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'save-as',
      action: 'save-as',
      keys: ['s'],
      modifiers: ['ctrl', 'shift'],
      label: '另存为',
      description: '项目另存为',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'open',
      action: 'open',
      keys: ['o'],
      modifiers: ['ctrl'],
      label: '打开',
      description: '打开项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'new-project',
      action: 'new-project',
      keys: ['n'],
      modifiers: ['ctrl'],
      label: '新建项目',
      description: '创建新项目',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'import-media',
      action: 'import-media',
      keys: ['i'],
      modifiers: ['ctrl'],
      label: '导入媒体',
      description: '导入媒体文件',
      category: '文件',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'mark-in',
      action: 'mark-in',
      keys: ['I'],
      modifiers: [],
      label: '入点',
      description: '设置入点',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'mark-out',
      action: 'mark-out',
      keys: ['O'],
      modifiers: [],
      label: '出点',
      description: '设置出点',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'clear-marks',
      action: 'clear-marks',
      keys: ['D'],
      modifiers: ['ctrl'],
      label: '清除标记',
      description: '清除入点和出点',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'add-marker',
      action: 'add-marker',
      keys: ['M'],
      modifiers: [],
      label: '添加标记',
      description: '在当前位置添加标记',
      category: '标记',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'toggle-mute',
      action: 'toggle-mute',
      keys: ['M'],
      modifiers: ['ctrl'],
      label: '静音',
      description: '切换静音状态',
      category: '音频',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'volume-up',
      action: 'volume-up',
      keys: [']'],
      modifiers: ['ctrl'],
      label: '增加音量',
      description: '增加音量',
      category: '音频',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'volume-down',
      action: 'volume-down',
      keys: ['['],
      modifiers: ['ctrl'],
      label: '降低音量',
      description: '降低音量',
      category: '音频',
      enabled: true,
      customizable: true,
      context: 'global',
    },
    {
      id: 'toggle-loop',
      action: 'toggle-loop',
      keys: ['L'],
      modifiers: ['ctrl'],
      label: '循环',
      description: '切换循环播放',
      category: '播放控制',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'toggle-snapping',
      action: 'toggle-snapping',
      keys: ['N'],
      modifiers: ['ctrl'],
      label: '吸附',
      description: '切换吸附功能',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'nudge-left',
      action: 'nudge-left',
      keys: [','],
      modifiers: ['ctrl'],
      label: '左微调',
      description: '向左微调片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
    {
      id: 'nudge-right',
      action: 'nudge-right',
      keys: ['.'],
      modifiers: ['ctrl'],
      label: '右微调',
      description: '向右微调片段',
      category: '编辑',
      enabled: true,
      customizable: true,
      context: 'timeline',
    },
  ],
};

/** 所有预设方案 */
export const ALL_SHORTCUT_SCHEMES: ShortcutScheme[] = [PREMIERE_SCHEME, FINAL_CUT_SCHEME, DAVINCI_RESOLVE_SCHEME];
