import type {
  PluginRegistryEntry,
  PluginReview,
  PluginVersionInfo,
  PluginCategory,
} from '@open-factory/plugin-market';

// ─── Category metadata ──────────────────────────────────────────────

export interface CategoryMeta {
  readonly id: PluginCategory | 'all';
  readonly name: string;
  readonly icon: string;
  readonly count: number;
}

export const mockCategories: readonly CategoryMeta[] = [
  { id: 'all', name: 'All Plugins', icon: '🧩', count: 14 },
  { id: 'effect', name: 'Effects', icon: '✨', count: 4 },
  { id: 'transition', name: 'Transitions', icon: '🔀', count: 1 },
  { id: 'generator', name: 'Generators', icon: '⚡', count: 2 },
  { id: 'analyzer', name: 'Analyzers', icon: '📊', count: 1 },
  { id: 'exporter', name: 'Exporters', icon: '📤', count: 1 },
  { id: 'importer', name: 'Importers', icon: '📥', count: 1 },
  { id: 'tool', name: 'Tools', icon: '🔧', count: 1 },
  { id: 'workflow', name: 'Workflows', icon: '⚙️', count: 1 },
  { id: 'theme', name: 'Themes', icon: '🎨', count: 1 },
];

// ─── Mock plugins ────────────────────────────────────────────────────

export const mockPlugins: readonly PluginRegistryEntry[] = [
  {
    manifest: {
      id: 'cinematic-grade',
      name: 'Cinematic Grade',
      version: '1.2.0',
      description:
        'Professional color grading with LUT support, film emulation, and HDR tone mapping. Includes 50+ built-in cinematic presets for documentary, narrative, and commercial work.',
      author: 'ColorLab Studio',
      license: 'MIT',
      homepage: 'https://colorlab.studio',
      keywords: ['color', 'grading', 'lut', 'cinematic', 'hdr'],
      category: 'effect',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: { required: [], optional: [] },
      icon: '🎬',
      screenshots: [],
    },
    stats: {
      pluginId: 'cinematic-grade',
      downloads: 48200,
      weeklyDownloads: 3100,
      monthlyDownloads: 12400,
      activeInstalls: 28900,
      lastDownloadAt: '2026-07-22T10:00:00Z',
    },
    rating: {
      pluginId: 'cinematic-grade',
      averageRating: 4.8,
      totalReviews: 342,
      distribution: { 1: 7, 2: 17, 3: 34, 4: 86, 5: 198 },
    },
    publishedAt: '2025-11-15T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
    verified: true,
    deprecated: false,
  },
  {
    manifest: {
      id: 'smooth-transitions',
      name: 'Smooth Transitions Pack',
      version: '2.0.0',
      description:
        'Over 120 seamless transitions including morph, warp, parallax, and liquid effects. GPU-accelerated rendering.',
      author: 'TransitFX',
      license: 'MIT',
      keywords: ['transition', 'effects', 'morph', 'warp'],
      category: 'transition',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: { required: [], optional: [] },
      icon: '🌊',
      screenshots: [],
    },
    stats: {
      pluginId: 'smooth-transitions',
      downloads: 56700,
      weeklyDownloads: 4500,
      monthlyDownloads: 18000,
      activeInstalls: 34000,
      lastDownloadAt: '2026-07-22T09:30:00Z',
    },
    rating: {
      pluginId: 'smooth-transitions',
      averageRating: 4.9,
      totalReviews: 521,
      distribution: { 1: 5, 2: 10, 3: 31, 4: 104, 5: 371 },
    },
    publishedAt: '2025-09-05T00:00:00Z',
    updatedAt: '2026-06-28T00:00:00Z',
    verified: true,
    deprecated: false,
  },
  {
    manifest: {
      id: 'ai-subtitle-gen',
      name: 'AI Subtitle Generator',
      version: '3.0.0',
      description:
        'Automatic subtitle generation using AI speech recognition. Supports 50+ languages with high accuracy and real-time preview.',
      author: 'SpeechAI',
      license: 'Apache-2.0',
      keywords: ['ai', 'subtitle', 'speech', 'transcription'],
      category: 'generator',
      minHostVersion: '4.2.0',
      main: 'index.js',
      permissions: {
        required: [
          { category: 'network', target: 'https://api.speechai.com/*', operations: ['connect'] },
        ],
        optional: [],
      },
      icon: '🎤',
      screenshots: [],
    },
    stats: {
      pluginId: 'ai-subtitle-gen',
      downloads: 28500,
      weeklyDownloads: 1560,
      monthlyDownloads: 5800,
      activeInstalls: 15200,
      lastDownloadAt: '2026-07-21T14:00:00Z',
    },
    rating: {
      pluginId: 'ai-subtitle-gen',
      averageRating: 4.9,
      totalReviews: 412,
      distribution: { 1: 1, 2: 3, 3: 10, 4: 48, 5: 350 },
    },
    publishedAt: '2025-11-01T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    verified: true,
    deprecated: false,
  },
  {
    manifest: {
      id: 'motion-blur-pro',
      name: 'Motion Blur Pro',
      version: '1.5.0',
      description:
        'Advanced motion blur with per-object control, vector-based blur paths, and GPU acceleration.',
      author: 'MotionCraft',
      license: 'MIT',
      keywords: ['blur', 'motion', 'gpu', 'effect'],
      category: 'effect',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: { required: [], optional: [] },
      icon: '🌀',
      screenshots: [],
    },
    stats: {
      pluginId: 'motion-blur-pro',
      downloads: 31500,
      weeklyDownloads: 2200,
      monthlyDownloads: 8800,
      activeInstalls: 18900,
      lastDownloadAt: '2026-07-22T08:15:00Z',
    },
    rating: {
      pluginId: 'motion-blur-pro',
      averageRating: 4.6,
      totalReviews: 189,
      distribution: { 1: 4, 2: 9, 3: 19, 4: 57, 5: 100 },
    },
    publishedAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-06-15T00:00:00Z',
    verified: true,
    deprecated: false,
  },
  {
    manifest: {
      id: 'ai-scene-detect',
      name: 'AI Scene Detection',
      version: '2.1.0',
      description:
        'Machine learning powered scene detection with automatic cut point suggestions and content classification.',
      author: 'VisionAI Labs',
      license: 'MIT',
      keywords: ['ai', 'scene', 'detection', 'ml'],
      category: 'analyzer',
      minHostVersion: '4.1.0',
      main: 'index.js',
      permissions: {
        required: [
          { category: 'process', target: 'tensorflow', operations: ['execute'] },
        ],
        optional: [],
      },
      icon: '🤖',
      screenshots: [],
    },
    stats: {
      pluginId: 'ai-scene-detect',
      downloads: 22400,
      weeklyDownloads: 1800,
      monthlyDownloads: 7200,
      activeInstalls: 13400,
      lastDownloadAt: '2026-07-21T16:30:00Z',
    },
    rating: {
      pluginId: 'ai-scene-detect',
      averageRating: 4.7,
      totalReviews: 156,
      distribution: { 1: 3, 2: 8, 3: 16, 4: 47, 5: 82 },
    },
    publishedAt: '2026-03-10T00:00:00Z',
    updatedAt: '2026-07-10T00:00:00Z',
    verified: true,
    deprecated: false,
  },
  {
    manifest: {
      id: 'particle-gen',
      name: 'Particle Generator',
      version: '1.3.0',
      description:
        'Real-time particle system for rain, snow, fire, sparks, and custom particle effects with physics simulation.',
      author: 'FXForge',
      license: 'MIT',
      keywords: ['particles', 'effects', 'rain', 'fire'],
      category: 'generator',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: { required: [], optional: [] },
      icon: '🎆',
      screenshots: [],
    },
    stats: {
      pluginId: 'particle-gen',
      downloads: 19800,
      weeklyDownloads: 1400,
      monthlyDownloads: 5600,
      activeInstalls: 11800,
      lastDownloadAt: '2026-07-21T12:00:00Z',
    },
    rating: {
      pluginId: 'particle-gen',
      averageRating: 4.5,
      totalReviews: 98,
      distribution: { 1: 2, 2: 5, 3: 10, 4: 30, 5: 51 },
    },
    publishedAt: '2026-02-28T00:00:00Z',
    updatedAt: '2026-05-20T00:00:00Z',
    verified: false,
    deprecated: false,
  },
  {
    manifest: {
      id: 'subtitle-sync',
      name: 'Subtitle Sync Pro',
      version: '2.2.0',
      description:
        'Auto-sync subtitles with speech detection, SRT/SUB/ASS import/export, and translation pipeline.',
      author: 'SubWorks',
      license: 'MIT',
      keywords: ['subtitles', 'caption', 'sync', 'speech'],
      category: 'tool',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: { required: [], optional: [] },
      icon: '💬',
      screenshots: [],
    },
    stats: {
      pluginId: 'subtitle-sync',
      downloads: 41200,
      weeklyDownloads: 2800,
      monthlyDownloads: 11200,
      activeInstalls: 24700,
      lastDownloadAt: '2026-07-22T07:45:00Z',
    },
    rating: {
      pluginId: 'subtitle-sync',
      averageRating: 4.4,
      totalReviews: 267,
      distribution: { 1: 8, 2: 13, 3: 40, 4: 80, 5: 126 },
    },
    publishedAt: '2025-12-01T00:00:00Z',
    updatedAt: '2026-06-10T00:00:00Z',
    verified: true,
    deprecated: false,
  },
  {
    manifest: {
      id: 'prores-exporter',
      name: 'ProRes Exporter',
      version: '1.1.0',
      description:
        'Export to Apple ProRes 422/4444 with hardware encoding support and custom presets.',
      author: 'CodecWorks',
      license: 'MIT',
      keywords: ['prores', 'export', 'apple', 'codec'],
      category: 'exporter',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: { required: [], optional: [] },
      icon: '📦',
      screenshots: [],
    },
    stats: {
      pluginId: 'prores-exporter',
      downloads: 28900,
      weeklyDownloads: 1900,
      monthlyDownloads: 7600,
      activeInstalls: 17300,
      lastDownloadAt: '2026-07-21T18:00:00Z',
    },
    rating: {
      pluginId: 'prores-exporter',
      averageRating: 4.3,
      totalReviews: 134,
      distribution: { 1: 4, 2: 7, 3: 20, 4: 40, 5: 63 },
    },
    publishedAt: '2026-04-15T00:00:00Z',
    updatedAt: '2026-07-05T00:00:00Z',
    verified: true,
    deprecated: false,
  },
  {
    manifest: {
      id: 'audio-visualizer',
      name: 'Audio Visualizer',
      version: '1.2.0',
      description:
        'Generate waveform, spectrum, and circular visualizations synced to audio tracks.',
      author: 'AudioViz',
      license: 'MIT',
      keywords: ['audio', 'visualizer', 'waveform', 'spectrum'],
      category: 'generator',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: { required: [], optional: [] },
      icon: '🎵',
      screenshots: [],
    },
    stats: {
      pluginId: 'audio-visualizer',
      downloads: 15600,
      weeklyDownloads: 1100,
      monthlyDownloads: 4400,
      activeInstalls: 9300,
      lastDownloadAt: '2026-07-20T20:00:00Z',
    },
    rating: {
      pluginId: 'audio-visualizer',
      averageRating: 4.6,
      totalReviews: 87,
      distribution: { 1: 2, 2: 4, 3: 9, 4: 26, 5: 46 },
    },
    publishedAt: '2026-05-20T00:00:00Z',
    updatedAt: '2026-07-08T00:00:00Z',
    verified: false,
    deprecated: false,
  },
  {
    manifest: {
      id: 'workflow-automator',
      name: 'Workflow Automator',
      version: '1.0.0',
      description:
        'Visual workflow editor for batch processing, conditional exports, and multi-step render pipelines.',
      author: 'AutoFlow',
      license: 'MIT',
      keywords: ['workflow', 'automation', 'batch', 'pipeline'],
      category: 'workflow',
      minHostVersion: '4.2.0',
      main: 'index.js',
      permissions: { required: [], optional: [] },
      icon: '⚙️',
      screenshots: [],
    },
    stats: {
      pluginId: 'workflow-automator',
      downloads: 12300,
      weeklyDownloads: 890,
      monthlyDownloads: 3560,
      activeInstalls: 7400,
      lastDownloadAt: '2026-07-21T10:00:00Z',
    },
    rating: {
      pluginId: 'workflow-automator',
      averageRating: 4.2,
      totalReviews: 56,
      distribution: { 1: 2, 2: 3, 3: 8, 4: 17, 5: 26 },
    },
    publishedAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-15T00:00:00Z',
    verified: false,
    deprecated: false,
  },
  {
    manifest: {
      id: 'neon-theme',
      name: 'Neon Dark Theme',
      version: '1.0.0',
      description:
        'A cyberpunk-inspired dark theme with neon accent colors, glowing UI elements, and custom cursors.',
      author: 'ThemeCraft',
      license: 'MIT',
      keywords: ['theme', 'dark', 'neon', 'cyberpunk'],
      category: 'theme',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: {
        required: [{ category: 'ui', target: 'theme', operations: ['write'] }],
        optional: [],
      },
      icon: '🌃',
      screenshots: [],
    },
    stats: {
      pluginId: 'neon-theme',
      downloads: 8700,
      weeklyDownloads: 650,
      monthlyDownloads: 2600,
      activeInstalls: 5200,
      lastDownloadAt: '2026-07-20T15:00:00Z',
    },
    rating: {
      pluginId: 'neon-theme',
      averageRating: 4.1,
      totalReviews: 43,
      distribution: { 1: 1, 2: 2, 3: 6, 4: 13, 5: 21 },
    },
    publishedAt: '2026-06-15T00:00:00Z',
    updatedAt: '2026-07-12T00:00:00Z',
    verified: false,
    deprecated: false,
  },
  {
    manifest: {
      id: 'json-importer',
      name: 'JSON Data Importer',
      version: '1.1.0',
      description:
        'Import structured data from JSON/CSV/XML to create data-driven overlays and lower thirds.',
      author: 'DataViz Tools',
      license: 'MIT',
      keywords: ['json', 'csv', 'import', 'data'],
      category: 'importer',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: {
        required: [{ category: 'filesystem', target: '/data/*', operations: ['read'] }],
        optional: [],
      },
      icon: '📋',
      screenshots: [],
    },
    stats: {
      pluginId: 'json-importer',
      downloads: 9400,
      weeklyDownloads: 720,
      monthlyDownloads: 2880,
      activeInstalls: 5600,
      lastDownloadAt: '2026-07-21T11:00:00Z',
    },
    rating: {
      pluginId: 'json-importer',
      averageRating: 4.0,
      totalReviews: 38,
      distribution: { 1: 1, 2: 2, 3: 6, 4: 12, 5: 17 },
    },
    publishedAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-06-20T00:00:00Z',
    verified: false,
    deprecated: false,
  },
  {
    manifest: {
      id: 'lens-flare-studio',
      name: 'Lens Flare Studio',
      version: '1.4.0',
      description:
        'Photorealistic lens flare and light leak effects with real-time preview and animation controls.',
      author: 'LightWorks',
      license: 'MIT',
      keywords: ['lens', 'flare', 'light', 'effect'],
      category: 'effect',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: { required: [], optional: [] },
      icon: '💡',
      screenshots: [],
    },
    stats: {
      pluginId: 'lens-flare-studio',
      downloads: 25100,
      weeklyDownloads: 1700,
      monthlyDownloads: 6800,
      activeInstalls: 15000,
      lastDownloadAt: '2026-07-22T06:00:00Z',
    },
    rating: {
      pluginId: 'lens-flare-studio',
      averageRating: 4.7,
      totalReviews: 203,
      distribution: { 1: 4, 2: 10, 3: 20, 4: 51, 5: 118 },
    },
    publishedAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-06-25T00:00:00Z',
    verified: true,
    deprecated: false,
  },
  {
    manifest: {
      id: 'speed-ramp',
      name: 'Speed Ramp',
      version: '2.0.0',
      description:
        'Time remapping with smooth speed curves, frame interpolation, and freeze frame support.',
      author: 'TimeWarp',
      license: 'MIT',
      keywords: ['speed', 'slowmo', 'timewarp', 'ramp'],
      category: 'effect',
      minHostVersion: '4.0.0',
      main: 'index.js',
      permissions: { required: [], optional: [] },
      icon: '⏱️',
      screenshots: [],
    },
    stats: {
      pluginId: 'speed-ramp',
      downloads: 33200,
      weeklyDownloads: 2400,
      monthlyDownloads: 9600,
      activeInstalls: 19900,
      lastDownloadAt: '2026-07-22T09:00:00Z',
    },
    rating: {
      pluginId: 'speed-ramp',
      averageRating: 4.8,
      totalReviews: 278,
      distribution: { 1: 3, 2: 8, 3: 22, 4: 69, 5: 176 },
    },
    publishedAt: '2025-10-20T00:00:00Z',
    updatedAt: '2026-07-02T00:00:00Z',
    verified: true,
    deprecated: false,
  },
];

export const mockFeatured: readonly PluginRegistryEntry[] = [
  mockPlugins[0], // Cinematic Grade
  mockPlugins[1], // Smooth Transitions
  mockPlugins[2], // AI Subtitle Generator
];

// ─── Mock reviews ────────────────────────────────────────────────────

export const mockReviews: readonly PluginReview[] = [
  {
    id: 'r1',
    pluginId: 'cinematic-grade',
    userId: 'u1',
    userName: 'Alex Rivera',
    rating: 5,
    title: 'Best color grading plugin',
    content:
      'Transformed my workflow completely. The LUT presets are production-ready and the HDR tone mapping is incredibly accurate.',
    version: '1.2.0',
    createdAt: '2026-07-10T14:30:00Z',
    updatedAt: '2026-07-10T14:30:00Z',
    helpful: 24,
    reported: false,
  },
  {
    id: 'r2',
    pluginId: 'cinematic-grade',
    userId: 'u2',
    userName: 'Mika Tanaka',
    rating: 4,
    title: 'Great but could use more presets',
    content:
      'Excellent quality output. I wish there were more documentary-style presets, but the manual controls more than make up for it.',
    version: '1.1.0',
    createdAt: '2026-06-22T09:15:00Z',
    updatedAt: '2026-06-22T09:15:00Z',
    helpful: 11,
    reported: false,
  },
  {
    id: 'r3',
    pluginId: 'cinematic-grade',
    userId: 'u3',
    userName: 'Jordan Blake',
    rating: 5,
    title: 'Professional results, easy to use',
    content:
      'The real-time preview makes tweaking colors a breeze. Export quality is indistinguishable from DaVinci Resolve for most use cases.',
    version: '1.2.0',
    createdAt: '2026-07-18T16:45:00Z',
    updatedAt: '2026-07-18T16:45:00Z',
    helpful: 18,
    reported: false,
  },
  {
    id: 'r4',
    pluginId: 'cinematic-grade',
    userId: 'u4',
    userName: 'Sam Okonkwo',
    rating: 3,
    title: 'Good but heavy on resources',
    content:
      'The grading quality is solid, but it uses a lot of GPU memory on longer timelines. Would love to see optimization improvements.',
    version: '1.2.0',
    createdAt: '2026-07-05T11:20:00Z',
    updatedAt: '2026-07-05T11:20:00Z',
    helpful: 7,
    reported: false,
  },
  {
    id: 'r5',
    pluginId: 'smooth-transitions',
    userId: 'u5',
    userName: 'FilmMaker42',
    rating: 5,
    title: 'Essential for any editor',
    content:
      'The morph transition alone is worth the install. 120+ transitions and every single one looks professional.',
    version: '2.0.0',
    createdAt: '2026-07-15T10:00:00Z',
    updatedAt: '2026-07-15T10:00:00Z',
    helpful: 56,
    reported: false,
  },
  {
    id: 'r6',
    pluginId: 'ai-subtitle-gen',
    userId: 'u6',
    userName: 'ContentCreator',
    rating: 5,
    title: 'Saves hours of work',
    content:
      'The accuracy is incredible. I used to spend hours on subtitles, now it takes minutes. The multi-language support is a game changer.',
    version: '3.0.0',
    createdAt: '2026-07-10T08:30:00Z',
    updatedAt: '2026-07-10T08:30:00Z',
    helpful: 42,
    reported: false,
  },
];

// ─── Mock version history ────────────────────────────────────────────

export const mockVersions: readonly PluginVersionInfo[] = [
  {
    pluginId: 'cinematic-grade',
    version: '1.2.0',
    changelog:
      'Added HDR tone mapping engine, 15 new cinematic presets, GPU memory optimization for long timelines.',
    publishedAt: '2026-07-01T00:00:00Z',
    checksum: 'sha256:a1b2c3d4e5f6',
    dependencies: {},
    minHostVersion: '4.0.0',
  },
  {
    pluginId: 'cinematic-grade',
    version: '1.1.0',
    changelog:
      'Added batch LUT application, improved color accuracy for Rec.2020, fixed export artifacts on Windows.',
    publishedAt: '2026-04-15T00:00:00Z',
    checksum: 'sha256:b2c3d4e5f6g7',
    dependencies: {},
    minHostVersion: '3.8.0',
  },
  {
    pluginId: 'cinematic-grade',
    version: '1.0.0',
    changelog:
      'Initial release with 35 cinematic presets, LUT import/export, and real-time preview.',
    publishedAt: '2025-11-15T00:00:00Z',
    checksum: 'sha256:c3d4e5f6g7h8',
    dependencies: {},
    minHostVersion: '3.5.0',
  },
];
