import { finiteOrDefault } from '../math-utils';
export { finiteOrDefault };
import type { AiPipPlacementSuggestion, AudioChannelRoutingMode, AudioFadeCurve, BeatMarker, ChromaKey, ClipAILookMatch, ClipAILocalDenoise, ClipAudioDenoise, ClipBorder, ClipFrameInterpolation, ClipKeyframes, ClipMask, ClipMaskKeyframe, ClipPanoramaView, ClipPrivacyBlur, ClipProjection, ClipQualityEnhancement, ClipSlowMotionMode, ClipStabilization, ClipVideoRestoration, ColorCorrection, MotionTrackPoint, MulticamSequence, PrivacyBlurEffect, TextPathOptions, VideoDeinterlaceMode, VideoDenoisePreset } from '../model-types';
export declare function createId(prefix?: string): string;
export declare function normalizeClipBeatMarkers(markers: BeatMarker[] | undefined, maxTime?: number): BeatMarker[] | undefined;
export declare function normalizeDetectedBpm(bpm: number | undefined): number | undefined;
export declare function normalizeClipSceneCuts(cuts: number[] | undefined, maxTime?: number): number[] | undefined;
export declare function clampClipSpeed(speed: number | undefined): number;
export declare function normalizeColorCorrection(colorCorrection: Partial<ColorCorrection> | undefined): ColorCorrection;
export declare function normalizeChromaKey(chromaKey: Partial<ChromaKey> | undefined): ChromaKey;
export declare function isChromaKeyEnabled(chromaKey: Partial<ChromaKey> | undefined): boolean;
export declare function normalizeStabilization(stabilization: Partial<ClipStabilization> | undefined): ClipStabilization;
export declare function isStabilizationExportable(stabilization: Partial<ClipStabilization> | undefined): boolean;
export declare function normalizeFrameInterpolation(frameInterpolation: Partial<ClipFrameInterpolation> | undefined): ClipFrameInterpolation;
export declare function normalizeSlowMotionMode(mode: ClipSlowMotionMode | string | undefined): ClipSlowMotionMode;
export declare function normalizeClipProjection(projection: ClipProjection | string | undefined): ClipProjection;
export declare function normalizeClipPanoramaView(panorama: Partial<ClipPanoramaView> | undefined): ClipPanoramaView;
export declare function normalizeVideoDenoisePreset(preset: VideoDenoisePreset | string | undefined): VideoDenoisePreset;
export declare function normalizeVideoRestoration(restoration: Partial<ClipVideoRestoration> | undefined): ClipVideoRestoration;
export declare function suggestDeinterlaceMode(fieldOrder: string | null | undefined): VideoDeinterlaceMode | null;
export declare function normalizeQualityEnhancement(enhancement: Partial<ClipQualityEnhancement> | undefined): ClipQualityEnhancement;
export declare function normalizeMotionTrack(points: readonly Partial<MotionTrackPoint>[] | undefined, duration?: number): MotionTrackPoint[] | undefined;
export declare function normalizeAudioDenoise(audioDenoise: Partial<ClipAudioDenoise> | undefined): ClipAudioDenoise;
export declare function normalizeAILocalDenoise(aiLocalDenoise: Partial<ClipAILocalDenoise> | undefined): ClipAILocalDenoise;
export declare function normalizeAudioChannelRouting(mode: AudioChannelRoutingMode | undefined): AudioChannelRoutingMode;
export declare function normalizeAudioPitchSemitones(semitones: number | undefined): number;
export declare function normalizeAudioFadeCurve(curve: AudioFadeCurve | undefined): AudioFadeCurve;
export declare function normalizeAudioFadeDuration(duration: number | undefined, clipDuration?: number): number;
export declare function createMask(mask?: Partial<ClipMask>): ClipMask;
export declare function normalizeMask(mask: Partial<ClipMask> | undefined): ClipMask;
export declare function normalizeMasks(masks: ClipMask[] | undefined): ClipMask[];
export declare function normalizeMaskKeyframes(keyframes: readonly Partial<ClipMaskKeyframe>[] | undefined): ClipMaskKeyframe[] | undefined;
export declare function normalizePrivacyBlur(privacyBlur: Partial<ClipPrivacyBlur> | undefined): ClipPrivacyBlur | undefined;
export declare function normalizePrivacyBlurEffect(effect: PrivacyBlurEffect | undefined): PrivacyBlurEffect;
export declare function normalizeClipBorder(border: Partial<ClipBorder> | undefined): ClipBorder;
export declare function normalizeTextPath(pathText: Partial<TextPathOptions> | undefined): TextPathOptions;
export declare function normalizeMulticamSequence(multicam: Partial<MulticamSequence> | undefined, duration?: number): MulticamSequence | undefined;
export declare function normalizeSequenceFrameRate(frameRate: number | undefined): number | undefined;
export declare function normalizePrivacyRedactions(input: unknown): import('../model-types').ClipPrivacyRedaction[];
export declare function normalizeAILookMatch(input: unknown): ClipAILookMatch | undefined;
export declare function normalizeAiPipSuggestion(input: unknown): AiPipPlacementSuggestion | undefined;
export declare function normalizeFlashWarnings(input: unknown): import('../flash-warning').FlashWarning[];
export declare function cloneClipKeyframesLocal(keyframes: ClipKeyframes | undefined): ClipKeyframes | undefined;
export declare function normalizeHexColor(color: string | undefined, fallback: string): string;
//# sourceMappingURL=clip-normalize.d.ts.map