import type { AudioFadeCurve, ChromaKey, ClipAudioDenoise, ClipAILocalDenoise, ClipBorder, ClipFrameInterpolation, ClipPanoramaView, ClipPrivacyBlur, ClipProjection, ClipQualityEnhancement, ClipSlowMotionMode, ClipStabilization, ClipVideoTemporalDenoise, ClipVideoRestoration, FrameInterpolationMode, FrameInterpolationTargetFps, PathPoint, ProjectSettings, SubtitleMode, SubtitleStyle, SubtitleTrackType, TextStyle, TextPathOptions, TrackCompressor, TrackEQ, TransitionType, VfrHandlingStrategy, VideoDenoisePreset } from '../model-types';
export declare const MAX_CHROMA_KEY_COLORS = 3;
export declare const DEFAULT_PROJECT_SETTINGS: ProjectSettings;
export declare function normalizeProjectSettings(settings: Partial<ProjectSettings> | undefined): ProjectSettings;
export declare function normalizeVfrHandlingStrategy(value: unknown): VfrHandlingStrategy;
export declare const DEFAULT_TRANSFORM: {
    x: number;
    y: number;
    scale: number;
    scaleX: number;
    scaleY: number;
    rotation: number;
    opacity: number;
};
export declare const DEFAULT_COLOR_CORRECTION: {
    inputColorSpace: "rec709";
    brightness: number;
    contrast: number;
    saturation: number;
    hue: number;
    lutPath: null;
    luts: never[];
    colorCurves: import("..").ColorCurves;
    threeWayColor: import("..").ThreeWayColor;
};
export declare const DEFAULT_CHROMA_KEY: ChromaKey;
export declare const DEFAULT_STABILIZATION: ClipStabilization;
export declare const FRAME_INTERPOLATION_TARGET_FPS: readonly FrameInterpolationTargetFps[];
export declare const FRAME_INTERPOLATION_MODES: readonly FrameInterpolationMode[];
export declare const DEFAULT_FRAME_INTERPOLATION: ClipFrameInterpolation;
export declare const CLIP_SLOW_MOTION_MODES: readonly ClipSlowMotionMode[];
export declare const DEFAULT_SLOW_MOTION_MODE: ClipSlowMotionMode;
export declare const DEFAULT_CLIP_PROJECTION: ClipProjection;
export declare const DEFAULT_CLIP_PANORAMA_VIEW: ClipPanoramaView;
export declare const VIDEO_TEMPORAL_DENOISE_PRESETS: Record<Exclude<VideoDenoisePreset, 'off' | 'custom'>, ClipVideoTemporalDenoise>;
export declare const DEFAULT_VIDEO_RESTORATION: ClipVideoRestoration;
export declare const DEFAULT_QUALITY_ENHANCEMENT: ClipQualityEnhancement;
export declare const DEFAULT_AUDIO_DENOISE: ClipAudioDenoise;
export declare const DEFAULT_AI_LOCAL_DENOISE: ClipAILocalDenoise;
export declare const DEFAULT_AUDIO_PITCH_SEMITONES = 0;
export declare const DEFAULT_AUDIO_REVERSE = false;
export declare const DEFAULT_AUDIO_FADE_CURVE: AudioFadeCurve;
export declare const DEFAULT_AUDIO_FADE_DURATION = 0;
export declare const DEFAULT_MASK: {
    type: "rect";
    x: number;
    y: number;
    w: number;
    h: number;
    inverted: boolean;
    feather: number;
    enabled: boolean;
};
export declare const DEFAULT_PRIVACY_BLUR: ClipPrivacyBlur;
export declare const DEFAULT_CLIP_BORDER: ClipBorder;
export declare const DEFAULT_TRACK_VOLUME = 1;
export declare const DEFAULT_TRACK_PAN = 0;
export declare const DEFAULT_MASTER_VOLUME = 1;
export declare const DEFAULT_TRACK_EQ: TrackEQ;
export declare const DEFAULT_TRACK_COMPRESSOR: TrackCompressor;
export declare const PRIMARY_SEQUENCE_ID = "sequence-main";
export declare const DEFAULT_PRIMARY_SEQUENCE_NAME = "Main Sequence";
export declare const DEFAULT_NESTED_SEQUENCE_NAME = "Nested Sequence";
export declare const MAX_NESTED_SEQUENCE_DEPTH = 3;
export declare const DEFAULT_TRANSITION_TYPE: TransitionType;
export declare const DEFAULT_TRANSITION_DURATION = 0.5;
export declare const MIN_TRANSITION_DURATION = 0.1;
export declare const MAX_TRANSITION_DURATION = 5;
export declare const TRANSITION_TYPES: TransitionType[];
export declare const DEFAULT_TIMELINE_MARKER_COLOR = "#f97316";
export declare const DEFAULT_PROJECT_ANNOTATION_COLOR = "#facc15";
export declare const DEFAULT_REVIEW_ANNOTATION_COLOR = "#facc15";
export declare const DEFAULT_COLLABORATION_NOTE_AUTHOR = "Collaborator";
export declare const DEFAULT_COLLABORATION_NOTE_COLOR = "#38bdf8";
export declare const PROJECT_ANNOTATION_COLORS: readonly ["#facc15", "#38bdf8", "#34d399", "#fb7185", "#a78bfa"];
export declare const TIMELINE_NOTE_COLORS: readonly ["#facc15", "#38bdf8", "#34d399", "#fb7185", "#a78bfa", "#fb923c"];
export declare const DEFAULT_TIMELINE_NOTE_COLOR: "#facc15";
export declare const MIN_CLIP_SPEED = 0.25;
export declare const MAX_CLIP_SPEED = 4;
export declare const DEFAULT_CLIP_SPEED = 1;
export declare const DEFAULT_TEXT_STYLE: TextStyle;
export declare const DEFAULT_TEXT_PATH_POINTS: PathPoint[];
export declare const DEFAULT_TEXT_PATH: TextPathOptions;
export declare const DEFAULT_SUBTITLE_MODE: SubtitleMode;
export declare const DEFAULT_SUBTITLE_LANGUAGE = "zh";
export declare const DEFAULT_SUBTITLE_TRACK_TYPE: SubtitleTrackType;
export declare const DEFAULT_SUBTITLE_STYLE: SubtitleStyle;
//# sourceMappingURL=defaults.d.ts.map