import type { AdjustmentClip, BaseClip, CollaborationNote, CreditsClip, ExportRange, MotionGraphicClip, MulticamClip, MulticamClipAngle, MulticamSyncMode, NestedSequenceClip, Project, ProjectAnnotation, ProtectedRange, ReviewAnnotation, Sequence, Subclip, SubtitleLanguage, SubtitleTrackType, Timeline, TimelineBookmark, TimelineMarker, TimelineNote, Track, TrackCompressor, TrackEQ, Transform, Transition } from '../model-types';
export declare function normalizeTransform(transform: Partial<Transform> | undefined): Transform;
export declare function normalizeTrackVolume(volume: number | undefined): number;
export declare function normalizeTrackPan(pan: number | undefined): number;
export declare function normalizeSubtitleLanguage(language: unknown): SubtitleLanguage;
export declare function normalizeSubtitleTrackType(value: unknown): SubtitleTrackType;
export declare function normalizeTrackEQ(eq: Partial<TrackEQ> | undefined): TrackEQ;
export declare function normalizeTrackCompressor(compressor: Partial<TrackCompressor> | undefined): TrackCompressor;
export declare function normalizeSequenceName(name: string | undefined): string;
export declare function createDefaultTimeline(): Timeline;
export declare function createTransition(transition: Omit<Transition, 'id' | 'type' | 'duration'> & Partial<Pick<Transition, 'id' | 'type' | 'duration'>>): Transition;
export declare function createTimelineMarker(marker: Omit<TimelineMarker, 'id' | 'label' | 'color'> & Partial<Pick<TimelineMarker, 'id' | 'label' | 'color'>>, maxTime?: number): TimelineMarker;
export declare function createTimelineBookmark(bookmark: Omit<TimelineBookmark, 'id' | 'note'> & Partial<Pick<TimelineBookmark, 'id' | 'note' | 'groupId' | 'thumbnailPath' | 'annotation' | 'createdAt'>>, maxTime?: number): TimelineBookmark;
export declare function createProjectAnnotation(annotation: Omit<ProjectAnnotation, 'id' | 'text' | 'color'> & Partial<Pick<ProjectAnnotation, 'id' | 'text' | 'color'>>, maxTime?: number): ProjectAnnotation;
export declare function createReviewAnnotation(annotation: Omit<ReviewAnnotation, 'id' | 'type' | 'text' | 'color' | 'x' | 'y' | 'width' | 'height'> & Partial<Pick<ReviewAnnotation, 'id' | 'type' | 'text' | 'color' | 'x' | 'y' | 'width' | 'height'>>, maxTime?: number): ReviewAnnotation;
export declare function createCollaborationNote(note: Omit<CollaborationNote, 'id' | 'type' | 'authorName' | 'authorColor' | 'text' | 'resolved' | 'createdAt'> & Partial<Pick<CollaborationNote, 'id' | 'type' | 'authorName' | 'authorColor' | 'text' | 'mediaPath' | 'resolved' | 'createdAt' | 'updatedAt'>>, maxTime?: number): CollaborationNote;
export declare function createTimelineNote(note: Omit<TimelineNote, 'id' | 'text' | 'color' | 'createdAt'> & Partial<Pick<TimelineNote, 'id' | 'text' | 'color' | 'createdAt'>>, maxTime?: number): TimelineNote;
export declare function createExportRange(range: Omit<ExportRange, 'id' | 'label'> & Partial<Pick<ExportRange, 'id' | 'label'>>, maxTime?: number): ExportRange;
export declare function createProtectedRange(range: Omit<ProtectedRange, 'id' | 'label'> & Partial<Pick<ProtectedRange, 'id' | 'label'>>, maxTime?: number): ProtectedRange;
export declare function createTrack(track: Omit<Track, 'language' | 'subtitleType' | 'color' | 'muted' | 'solo' | 'locked' | 'volume' | 'pan' | 'eq' | 'compressor'> & Partial<Pick<Track, 'language' | 'subtitleType' | 'color' | 'muted' | 'solo' | 'locked' | 'volume' | 'pan' | 'eq' | 'compressor'>>): Track;
export declare function createProject(name?: string): Project;
export declare function createSubclip(input: Omit<Subclip, 'id' | 'createdAt'> & Partial<Pick<Subclip, 'id' | 'createdAt'>>): Subclip;
export declare function createSequence(sequence: Omit<Sequence, 'id' | 'name'> & Partial<Pick<Sequence, 'id' | 'name'>>): Sequence;
export declare function createBaseClip(input: Omit<BaseClip, 'id' | 'transform' | 'speed' | 'colorCorrection'> & Partial<Pick<BaseClip, 'id' | 'transform' | 'speed' | 'colorCorrection'>>): BaseClip;
export declare function createNestedSequenceClip(input: Omit<NestedSequenceClip, 'id' | 'transform' | 'speed' | 'colorCorrection' | 'volume'> & Partial<Pick<NestedSequenceClip, 'id' | 'transform' | 'speed' | 'colorCorrection' | 'volume'>>): NestedSequenceClip;
export declare function createAdjustmentClip(input: Omit<AdjustmentClip, 'id' | 'type' | 'transform' | 'speed' | 'colorCorrection'> & Partial<Pick<AdjustmentClip, 'id' | 'transform' | 'speed' | 'colorCorrection'>>): AdjustmentClip;
export declare function createMotionGraphicClip(input: Omit<MotionGraphicClip, 'id' | 'type' | 'transform' | 'speed' | 'colorCorrection' | 'motionGraphic'> & Partial<Pick<MotionGraphicClip, 'id' | 'transform' | 'speed' | 'colorCorrection' | 'motionGraphic'>>): MotionGraphicClip;
export declare function createCreditsClip(input: Omit<CreditsClip, 'id' | 'type' | 'transform' | 'speed' | 'colorCorrection' | 'rows' | 'rollSpeed' | 'style'> & Partial<Pick<CreditsClip, 'id' | 'transform' | 'speed' | 'colorCorrection' | 'rows' | 'rollSpeed' | 'style'>>): CreditsClip;
export declare function createMulticamClip(angles: MulticamClipAngle[], syncMode: MulticamSyncMode, syncReferenceAngle: number): MulticamClip;
//# sourceMappingURL=factories.d.ts.map