export type { AIColorHistoryEntry } from '../model-types';
export type { ClipPrivacyRedaction, PrivacyRedactionType, RedactionKeyframe, ClipAILookMatch, WheelAdjustments, BeatSnapSuggestion, MediaCollection, } from '../model-types';
export type { AdjustmentClip, AssetType, AudioChannelRoutingMode, AudioClip, AudioFadeCurve, BaseClip, ChromaKey, ChromaKeyColor, ChromaKeyMode, Clip, ClipAudioDenoise, ClipAudioRestoration, ClipAudioRestorationGap, ClipBorder, ClipFrameInterpolation, ClipGroup, ClipGroupColor, ClipKeyframes, ClipMask, ClipMaskKeyframe, ClipPanoramaOutputProjection, ClipPitchDataPoint, ClipPanoramaView, ClipPrivacyBlur, ClipProjection, ClipQualityEnhancement, ClipSlowMotionMode, ClipStabilization, ClipType, ClipVideoDeinterlace, ClipVideoRestoration, ClipVideoSpatialDenoise, ClipVideoTemporalDenoise, CollaborationNote, CollaborationNoteType, ColorCorrection, CreditsClip, DataSubtitleClip, DataSubtitleRow, DataSubtitleSource, DataSubtitleSourceType, ExportRange, FrameInterpolationMode, FrameInterpolationQuality, FrameInterpolationQualityGrade, FrameInterpolationTargetFps, ImageClip, ImageSequenceInfo, Keyframe, KeyframeEasing, KeyframeHandle, KeyframeHandleMode, KeyframeProperty, LUTLayer, Mask, MaskType, MediaAsset, MediaFingerprint, MediaFingerprintAlgorithm, MediaFingerprintKind, MediaFlag, MediaFolder, MediaLabelColor, MediaMetadata, MotionTrackPoint, MotionGraphicClip, MulticamAngle, MulticamClip, MulticamClipAngle, MulticamSequence, MulticamSwitch, MulticamSyncMode, NestedSequenceClip, PathPoint, PathPointHandle, PrivacyBlurEffect, Project, ProjectAnnotation, ProjectDocumentation, ProjectSettings, ProjectSpeaker, ProjectVersion, ProtectedRange, ReviewAnnotation, ReviewAnnotationType, RichTextDocument, RichTextParagraph, RichTextRun, Sequence, SequenceSettings, Subclip, SubtitleClip, SubtitleLanguage, SubtitleMode, SubtitleStyle, SubtitleTrackType, SwitchPoint, SwitchTransition, TextArcOptions, TextBoxFitMode, TextClip, TextLayoutOptions, TextOpenTypeFeatures, TextPathOptions, TextStyle, Timeline, TimelineBookmark, TimelineMarker, TimelineNote, Track, TrackCompressor, TrackEQ, TrackEQBand, TrackEQBandType, TrackType, Transform, Transition, TransitionType, VfrHandlingStrategy, VideoClip, VideoDeinterlaceMode, VideoDenoisePreset, ZoomEditMode, } from '../model-types';
export type { TtsSegment, TimingAdaptation, DubbingAdaptationType } from '../model-types';
import { type MediaColorProfile } from '../color-management';
import type { MediaFingerprint, MediaFlag, MediaLabelColor, MediaMetadata } from '../model-types';
import type { ProjectFile } from '../project/project-types';
export declare function isMediaLabelColor(value: unknown): value is MediaLabelColor;
export declare function normalizeMediaRating(value: unknown): number;
export declare function normalizeMediaFlag(value: unknown): MediaFlag | undefined;
export declare function normalizeMediaFingerprint(value: unknown): MediaFingerprint | undefined;
export declare function normalizeMediaMetadataEntry(metadata: MediaMetadata | undefined): MediaMetadata | undefined;
export declare function normalizeMediaColorProfile(profile: Partial<MediaColorProfile> | undefined): MediaColorProfile | undefined;
export type CutProjectFile = ProjectFile;
//# sourceMappingURL=media-normalize.d.ts.map