import { finiteOrDefault } from '../math-utils';
export { finiteOrDefault };
import type { ChromaKey, ChromaKeyColor, ChromaKeyMode, ClipQualityEnhancement, CollaborationNote, ColorCorrection, ExportRange, PathPoint, Project, ProjectAnnotation, ProjectSpeaker, ProtectedRange, ReviewAnnotation, Sequence, SubtitleLanguage, SubtitleTrackType, Timeline, TimelineBookmark, TimelineMarker, TimelineNote, TrackCompressor, TrackEQ, TrackEQBand, TrackEQBandType, Transform, TransitionType } from '../model-types';
export declare function normalizeTimelineMarker(marker: TimelineMarker, maxTime?: number): TimelineMarker;
export declare function normalizeQualityEnhancement(enhancement: Partial<ClipQualityEnhancement> | undefined): ClipQualityEnhancement;
export declare function normalizeTimelineBookmark(bookmark: TimelineBookmark, maxTime?: number): TimelineBookmark;
export declare function normalizeTransform(transform: Partial<Transform> | undefined): Transform;
export declare function normalizeRotation(rotation: number | undefined): number;
export declare function getTransformScaleX(transform: Partial<Transform> | undefined): number;
export declare function getTransformScaleY(transform: Partial<Transform> | undefined): number;
export declare function clampTransformScale(scale: number | undefined, fallback: number): number;
export declare function normalizeTimelineMarkers(markers: TimelineMarker[] | undefined, maxTime?: number): TimelineMarker[];
export declare function normalizeTimelineBookmarks(bookmarks: TimelineBookmark[] | undefined, maxTime?: number): TimelineBookmark[];
export declare function normalizeProjectAnnotation(annotation: ProjectAnnotation, maxTime?: number): ProjectAnnotation;
export declare function normalizeProjectAnnotations(annotations: ProjectAnnotation[] | undefined, maxTime?: number): ProjectAnnotation[];
export declare function normalizeReviewAnnotation(annotation: ReviewAnnotation, maxTime?: number): ReviewAnnotation;
export declare function normalizeReviewAnnotations(annotations: ReviewAnnotation[] | undefined, maxTime?: number): ReviewAnnotation[];
export declare function normalizeCollaborationNote(note: CollaborationNote, maxTime?: number): CollaborationNote;
export declare function normalizeCollaborationNotes(notes: CollaborationNote[] | undefined, maxTime?: number): CollaborationNote[];
export declare function normalizeTimelineNote(note: TimelineNote, maxTime?: number): TimelineNote | undefined;
export declare function normalizeTimelineNotes(notes: TimelineNote[] | undefined, maxTime?: number): TimelineNote[];
export declare function normalizeExportRange(range: ExportRange, maxTime?: number): ExportRange | undefined;
export declare function normalizeExportRanges(ranges: ExportRange[] | undefined, maxTime?: number): ExportRange[];
export declare function normalizeProtectedRange(range: ProtectedRange, maxTime?: number): ProtectedRange | undefined;
export declare function normalizeProtectedRanges(ranges: ProtectedRange[] | undefined, maxTime?: number): ProtectedRange[];
export declare function normalizeTrackVolume(volume: number | undefined): number;
export declare function normalizeTrackPan(pan: number | undefined): number;
export declare function normalizeSubtitleLanguage(language: unknown): SubtitleLanguage;
export declare function normalizeSubtitleTrackType(value: unknown): SubtitleTrackType;
export declare function normalizeSubtitleSpeaker(value: unknown): string | undefined;
export declare function normalizeSubtitleSoundDesc(value: unknown): string | undefined;
export declare function normalizeProjectSpeakers(speakers: unknown): ProjectSpeaker[];
export declare function normalizeSubtitleLanguageList(languages: unknown): SubtitleLanguage[] | undefined;
export declare function normalizeTrackEQ(eq: Partial<TrackEQ> | undefined): TrackEQ;
export declare function normalizeTrackEQBand(band: Partial<TrackEQBand> | undefined, fallback?: TrackEQBand): TrackEQBand;
export declare function normalizeTrackCompressor(compressor: Partial<TrackCompressor> | undefined): TrackCompressor;
export declare function normalizeMasterVolume(volume: number | undefined): number;
export declare function normalizeSequenceName(name: string | undefined): string;
export declare function getProjectSequences(project: Pick<Project, 'timeline' | 'sequences'>): Sequence[];
export declare function getProjectActiveSequenceId(project: Pick<Project, 'activeSequenceId' | 'sequences' | 'timeline'>): string;
export declare function getProjectPrimaryTimeline(project: Pick<Project, 'activeSequenceId' | 'timeline' | 'sequences'>): Timeline;
export declare function replaceProjectActiveTimeline(project: Project, timeline: Timeline): Project;
export declare function switchProjectActiveSequence(project: Project, sequenceId: string): Project;
export declare function getNestedSequenceDepth(project: Project, sequenceId?: string): number;
export declare function isNestedSequenceDepthExceeded(project: Project, sequenceId?: string, maxDepth?: number): boolean;
export declare function normalizeTrackEQBandType(type: TrackEQBandType | undefined, fallback: TrackEQBandType): TrackEQBandType;
export declare function normalizeRgbColor(color: ChromaKeyColor | readonly number[] | undefined): ChromaKeyColor;
export declare function normalizeChromaKeyColors(chromaKey: Partial<ChromaKey> | undefined): ChromaKeyColor[];
export declare function normalizeChromaKeyMode(mode: ChromaKeyMode | undefined): ChromaKeyMode;
export declare function normalizeRgbChannel(value: number | undefined): number;
export declare function clonePathPoint(point: PathPoint): PathPoint;
export declare function normalizeUnit(value: number | undefined, fallback: number): number;
export declare function normalizePositiveUnit(value: number | undefined, fallback: number): number;
export declare function getNestedSequenceDepthForTimeline(project: Project, timeline: Timeline, visited: Set<string>): number;
export declare function normalizeTransitionType(type: TransitionType | undefined): TransitionType;
export declare function normalizeTransitionDuration(duration: number | undefined): number;
export declare function isDefaultColorCorrection(colorCorrection: Partial<ColorCorrection> | undefined): boolean;
//# sourceMappingURL=track-timeline.d.ts.map