/**
 * Quality Inspector Types
 * Multi-dimensional quality detection framework for video/audio content
 */
/** Default inspector configuration */
export const DEFAULT_INSPECTOR_CONFIG = {
    enableTechnicalDetection: true,
    enableContentAnalysis: true,
    enableComplianceCheck: true,
    targetPlatform: 'youtube-1080p',
    blackFrameThreshold: 0.05,
    staticFrameThreshold: 0.02,
    clippingThresholdDb: -1,
    silenceThresholdDb: -50,
    slowPacingRatio: 0.6,
    fastPacingRatio: 1.8,
    frameSampleInterval: 0.5,
    audioSampleInterval: 0.1,
};
/** Platform specifications */
export const PLATFORM_SPECS = {
    'youtube-1080p': {
        id: 'youtube-1080p',
        name: 'YouTube 1080p',
        width: 1920,
        height: 1080,
        aspectRatio: 16 / 9,
        maxDuration: 43200,
        frameRate: 30,
        audioSampleRate: 48000,
        audioChannels: 2,
        videoBitrate: 8000000,
    },
    'youtube-4k': {
        id: 'youtube-4k',
        name: 'YouTube 4K',
        width: 3840,
        height: 2160,
        aspectRatio: 16 / 9,
        maxDuration: 43200,
        frameRate: 30,
        audioSampleRate: 48000,
        audioChannels: 2,
        videoBitrate: 35000000,
    },
    'tiktok-9-16': {
        id: 'tiktok-9-16',
        name: 'TikTok 9:16',
        width: 1080,
        height: 1920,
        aspectRatio: 9 / 16,
        maxDuration: 600,
        minDuration: 3,
        frameRate: 30,
        audioSampleRate: 44100,
        audioChannels: 2,
        audioBitrate: 128000,
    },
    'instagram-reel': {
        id: 'instagram-reel',
        name: 'Instagram Reel',
        width: 1080,
        height: 1920,
        aspectRatio: 9 / 16,
        maxDuration: 90,
        minDuration: 3,
        frameRate: 30,
        audioSampleRate: 44100,
        audioChannels: 2,
    },
    'twitter-video': {
        id: 'twitter-video',
        name: 'Twitter Video',
        width: 1280,
        height: 720,
        aspectRatio: 16 / 9,
        maxDuration: 140,
        frameRate: 30,
        audioSampleRate: 44100,
        audioChannels: 2,
        videoBitrate: 5000000,
    },
    'broadcast-pal': {
        id: 'broadcast-pal',
        name: 'Broadcast PAL',
        width: 1920,
        height: 1080,
        aspectRatio: 16 / 9,
        maxDuration: Infinity,
        frameRate: 25,
        audioSampleRate: 48000,
        audioChannels: 2,
        audioBitrate: 384000,
    },
    'broadcast-ntsc': {
        id: 'broadcast-ntsc',
        name: 'Broadcast NTSC',
        width: 1920,
        height: 1080,
        aspectRatio: 16 / 9,
        maxDuration: Infinity,
        frameRate: 29.97,
        audioSampleRate: 48000,
        audioChannels: 2,
        audioBitrate: 384000,
    },
    custom: {
        id: 'custom',
        name: 'Custom',
        width: 1920,
        height: 1080,
        aspectRatio: 16 / 9,
        maxDuration: Infinity,
        frameRate: 30,
        audioSampleRate: 48000,
        audioChannels: 2,
    },
};
//# sourceMappingURL=types.js.map