/**
 * AI Generator configuration
 */

import { z } from 'zod';
import type { ModelPrecision, ComputeBackend } from './types.js';

// ============================================================
// Config Schema
// ============================================================

const configSchema = z.object({
  // Model
  model: z.object({
    path: z.string().default('./models'),
    defaultPrecision: z.enum(['fp32', 'fp16', 'int8', 'int4']).default('int8'),
    cacheModels: z.boolean().default(true),
    maxCacheSize: z.number().default(4 * 1024 * 1024 * 1024), // 4GB
  }),

  // Compute
  compute: z.object({
    preferredBackend: z.enum(['webgpu', 'webgl', 'cpu']).default('webgpu'),
    fallbackEnabled: z.boolean().default(true),
    maxMemoryMB: z.number().default(4096),
    numThreads: z.number().default(navigator?.hardwareConcurrency || 4),
  }),

  // Generation
  generation: z.object({
    defaultWidth: z.number().default(1280),
    defaultHeight: z.number().default(720),
    defaultDuration: z.number().default(5),
    defaultFps: z.number().default(30),
    defaultSteps: z.number().default(30),
    defaultGuidanceScale: z.number().default(7.5),
    maxDuration: z.number().default(30),
    maxResolution: z.number().default(3840), // 4K
  }),

  // Safety
  safety: z.object({
    contentFilterEnabled: z.boolean().default(true),
    watermarkEnabled: z.boolean().default(true),
    watermarkText: z.string().default('Generated by Open Factory'),
    watermarkOpacity: z.number().default(0.3),
  }),

  // Usage
  usage: z.object({
    trackingEnabled: z.boolean().default(true),
    dailyLimitCheck: z.boolean().default(true),
  }),
});

export type GeneratorConfig = z.infer<typeof configSchema>;

// ============================================================
// Load Config
// ============================================================

export function loadConfig(overrides?: Partial<GeneratorConfig>): GeneratorConfig {
  const raw = {
    model: {
      path: process.env.AI_MODEL_PATH || './models',
      defaultPrecision: (process.env.AI_DEFAULT_PRECISION || 'int8') as ModelPrecision,
      cacheModels: process.env.AI_CACHE_MODELS !== 'false',
      maxCacheSize: parseInt(process.env.AI_MAX_CACHE_SIZE || '4294967296', 10),
    },
    compute: {
      preferredBackend: (process.env.AI_PREFERRED_BACKEND || 'webgpu') as ComputeBackend,
      fallbackEnabled: process.env.AI_FALLBACK_ENABLED !== 'false',
      maxMemoryMB: parseInt(process.env.AI_MAX_MEMORY_MB || '4096', 10),
      numThreads: parseInt(process.env.AI_NUM_THREADS || '4', 10),
    },
    generation: {
      defaultWidth: parseInt(process.env.AI_DEFAULT_WIDTH || '1280', 10),
      defaultHeight: parseInt(process.env.AI_DEFAULT_HEIGHT || '720', 10),
      defaultDuration: parseInt(process.env.AI_DEFAULT_DURATION || '5', 10),
      defaultFps: parseInt(process.env.AI_DEFAULT_FPS || '30', 10),
      defaultSteps: parseInt(process.env.AI_DEFAULT_STEPS || '30', 10),
      defaultGuidanceScale: parseFloat(process.env.AI_DEFAULT_GUIDANCE_SCALE || '7.5'),
      maxDuration: parseInt(process.env.AI_MAX_DURATION || '30', 10),
      maxResolution: parseInt(process.env.AI_MAX_RESOLUTION || '3840', 10),
    },
    safety: {
      contentFilterEnabled: process.env.AI_CONTENT_FILTER !== 'false',
      watermarkEnabled: process.env.AI_WATERMARK !== 'false',
      watermarkText: process.env.AI_WATERMARK_TEXT || 'Generated by Open Factory',
      watermarkOpacity: parseFloat(process.env.AI_WATERMARK_OPACITY || '0.3'),
    },
    usage: {
      trackingEnabled: process.env.AI_USAGE_TRACKING !== 'false',
      dailyLimitCheck: process.env.AI_DAILY_LIMIT_CHECK !== 'false',
    },
  };

  const merged = {
    ...raw,
    ...overrides,
    model: { ...raw.model, ...overrides?.model },
    compute: { ...raw.compute, ...overrides?.compute },
    generation: { ...raw.generation, ...overrides?.generation },
    safety: { ...raw.safety, ...overrides?.safety },
    usage: { ...raw.usage, ...overrides?.usage },
  };

  return configSchema.parse(merged);
}

// ============================================================
// Singleton Config
// ============================================================

let _config: GeneratorConfig | null = null;

export function getConfig(): GeneratorConfig {
  if (!_config) {
    _config = loadConfig();
  }
  return _config;
}

export function resetConfig(): void {
  _config = null;
}
