/**
 * Default theme configurations
 */

import type { ThemeConfig } from './types.js';

/** Default dark theme */
export const DEFAULT_DARK_THEME: ThemeConfig = {
  id: 'default-dark',
  name: '默认深色',
  description: '默认深色主题',
  mode: 'dark',
  isDefault: true,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  colors: {
    primary: '#3b82f6',
    secondary: '#8b5cf6',
    accent: '#06b6d4',
    success: '#22c55e',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#3b82f6',

    background: '#0f0f0f',
    backgroundSecondary: '#1a1a1a',
    backgroundTertiary: '#262626',
    surface: '#1e1e1e',
    surfaceVariant: '#2d2d2d',

    textPrimary: '#ffffff',
    textSecondary: '#a3a3a3',
    textTertiary: '#737373',
    textDisabled: '#525252',
    textInverse: '#0f0f0f',

    border: '#404040',
    borderLight: '#333333',
    borderHeavy: '#525252',

    hover: 'rgba(255, 255, 255, 0.08)',
    active: 'rgba(255, 255, 255, 0.12)',
    focus: 'rgba(59, 130, 246, 0.5)',
    selected: 'rgba(59, 130, 246, 0.2)',
    disabled: 'rgba(255, 255, 255, 0.3)',

    timeline: {
      background: '#141414',
      track: '#1e1e1e',
      clip: '#3b82f6',
      clipSelected: '#2563eb',
      clipHover: '#60a5fa',
      playhead: '#ef4444',
      marker: '#f59e0b',
      waveform: '#3b82f6',
      grid: '#262626',
      ruler: '#1e1e1e',
    },

    preview: {
      background: '#000000',
      border: '#333333',
      controls: '#ffffff',
      progressBar: '#3b82f6',
      timecode: '#ffffff',
    },

    media: {
      background: '#1e1e1e',
      thumbnail: '#2d2d2d',
      selected: '#3b82f6',
      hover: '#2d2d2d',
      info: '#a3a3a3',
    },

    effects: {
      background: '#1e1e1e',
      category: '#2d2d2d',
      effect: '#333333',
      applied: '#3b82f6',
      disabled: '#525252',
    },
  },

  timeline: {
    trackHeight: 60,
    trackSpacing: 2,
    trackBorderWidth: 1,
    trackBorderColor: '#333333',
    clipBorderRadius: 4,
    clipBorderWidth: 1,
    clipShadowBlur: 4,
    clipShadowColor: 'rgba(0, 0, 0, 0.3)',
    waveformHeight: 40,
    waveformColor: '#3b82f6',
    waveformGradientStart: '#3b82f6',
    waveformGradientEnd: '#2563eb',
    playheadWidth: 2,
    playheadColor: '#ef4444',
    playheadHandleSize: 12,
    playheadHandleColor: '#ef4444',
    markerSize: 8,
    markerColor: '#f59e0b',
    markerBorderColor: '#d97706',
    gridLineWidth: 1,
    gridLineColor: '#262626',
    gridLineDash: [4, 4],
    rulerHeight: 24,
    rulerFontSize: 10,
    rulerFontColor: '#a3a3a3',
    rulerTickColor: '#525252',
    zoomLevel: 1,
    pixelsPerSecond: 100,
  },

  layout: {
    panels: {
      menuBar: { visible: true, height: 32 },
      toolbar: { visible: true, height: 48 },
      timeline: { visible: true, height: 300, position: 'bottom' },
      preview: { visible: true, width: 400, position: 'left' },
      mediaPanel: { visible: true, width: 300, position: 'left' },
      effectsPanel: { visible: true, width: 300, position: 'right' },
      propertiesPanel: { visible: true, width: 300, position: 'right' },
      statusBar: { visible: true, height: 24 },
    },
    splitter: {
      width: 4,
      color: '#333333',
      hoverColor: '#3b82f6',
      activeColor: '#2563eb',
    },
    breakpoints: {
      mobile: 640,
      tablet: 768,
      desktop: 1024,
      wide: 1280,
    },
    grid: {
      columns: 12,
      gutter: 16,
      margin: 16,
    },
  },

  fonts: {
    families: {
      sans: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      serif: 'Georgia, Cambria, "Times New Roman", Times, serif',
      mono: 'JetBrains Mono, Fira Code, Consolas, monospace',
      display: 'Inter, sans-serif',
    },
    sizes: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
    },
    weights: {
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeights: {
      tight: 1.25,
      normal: 1.5,
      relaxed: 1.75,
      loose: 2,
    },
  },

  animations: {
    durations: {
      instant: 0,
      fast: 150,
      normal: 300,
      slow: 500,
      slower: 1000,
    },
    easings: {
      linear: 'linear',
      easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
      easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
      easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
      bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      elastic: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    },
    enabled: true,
    reducedMotion: false,
  },
};

/** Default light theme */
export const DEFAULT_LIGHT_THEME: ThemeConfig = {
  id: 'default-light',
  name: '默认浅色',
  description: '默认浅色主题',
  mode: 'light',
  isDefault: false,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  colors: {
    primary: '#2563eb',
    secondary: '#7c3aed',
    accent: '#0891b2',
    success: '#16a34a',
    warning: '#d97706',
    error: '#dc2626',
    info: '#2563eb',

    background: '#ffffff',
    backgroundSecondary: '#f5f5f5',
    backgroundTertiary: '#e5e5e5',
    surface: '#ffffff',
    surfaceVariant: '#f5f5f5',

    textPrimary: '#171717',
    textSecondary: '#525252',
    textTertiary: '#737373',
    textDisabled: '#a3a3a3',
    textInverse: '#ffffff',

    border: '#e5e5e5',
    borderLight: '#f5f5f5',
    borderHeavy: '#d4d4d4',

    hover: 'rgba(0, 0, 0, 0.04)',
    active: 'rgba(0, 0, 0, 0.08)',
    focus: 'rgba(37, 99, 235, 0.5)',
    selected: 'rgba(37, 99, 235, 0.1)',
    disabled: 'rgba(0, 0, 0, 0.3)',

    timeline: {
      background: '#f5f5f5',
      track: '#ffffff',
      clip: '#2563eb',
      clipSelected: '#1d4ed8',
      clipHover: '#3b82f6',
      playhead: '#dc2626',
      marker: '#d97706',
      waveform: '#2563eb',
      grid: '#e5e5e5',
      ruler: '#f5f5f5',
    },

    preview: {
      background: '#000000',
      border: '#e5e5e5',
      controls: '#ffffff',
      progressBar: '#2563eb',
      timecode: '#ffffff',
    },

    media: {
      background: '#ffffff',
      thumbnail: '#f5f5f5',
      selected: '#2563eb',
      hover: '#f5f5f5',
      info: '#525252',
    },

    effects: {
      background: '#ffffff',
      category: '#f5f5f5',
      effect: '#e5e5e5',
      applied: '#2563eb',
      disabled: '#a3a3a3',
    },
  },

  timeline: {
    trackHeight: 60,
    trackSpacing: 2,
    trackBorderWidth: 1,
    trackBorderColor: '#e5e5e5',
    clipBorderRadius: 4,
    clipBorderWidth: 1,
    clipShadowBlur: 2,
    clipShadowColor: 'rgba(0, 0, 0, 0.1)',
    waveformHeight: 40,
    waveformColor: '#2563eb',
    waveformGradientStart: '#2563eb',
    waveformGradientEnd: '#1d4ed8',
    playheadWidth: 2,
    playheadColor: '#dc2626',
    playheadHandleSize: 12,
    playheadHandleColor: '#dc2626',
    markerSize: 8,
    markerColor: '#d97706',
    markerBorderColor: '#b45309',
    gridLineWidth: 1,
    gridLineColor: '#e5e5e5',
    gridLineDash: [4, 4],
    rulerHeight: 24,
    rulerFontSize: 10,
    rulerFontColor: '#525252',
    rulerTickColor: '#a3a3a3',
    zoomLevel: 1,
    pixelsPerSecond: 100,
  },

  layout: {
    panels: {
      menuBar: { visible: true, height: 32 },
      toolbar: { visible: true, height: 48 },
      timeline: { visible: true, height: 300, position: 'bottom' },
      preview: { visible: true, width: 400, position: 'left' },
      mediaPanel: { visible: true, width: 300, position: 'left' },
      effectsPanel: { visible: true, width: 300, position: 'right' },
      propertiesPanel: { visible: true, width: 300, position: 'right' },
      statusBar: { visible: true, height: 24 },
    },
    splitter: {
      width: 4,
      color: '#e5e5e5',
      hoverColor: '#2563eb',
      activeColor: '#1d4ed8',
    },
    breakpoints: {
      mobile: 640,
      tablet: 768,
      desktop: 1024,
      wide: 1280,
    },
    grid: {
      columns: 12,
      gutter: 16,
      margin: 16,
    },
  },

  fonts: {
    families: {
      sans: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      serif: 'Georgia, Cambria, "Times New Roman", Times, serif',
      mono: 'JetBrains Mono, Fira Code, Consolas, monospace',
      display: 'Inter, sans-serif',
    },
    sizes: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
    },
    weights: {
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeights: {
      tight: 1.25,
      normal: 1.5,
      relaxed: 1.75,
      loose: 2,
    },
  },

  animations: {
    durations: {
      instant: 0,
      fast: 150,
      normal: 300,
      slow: 500,
      slower: 1000,
    },
    easings: {
      linear: 'linear',
      easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
      easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
      easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
      bounce: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
      elastic: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    },
    enabled: true,
    reducedMotion: false,
  },
};
