/**
 * ffmpeg-builder — barrel re-export entry point
 *
 * Original monolithic file split into domain modules.
 * All public symbols re-exported here for backward compatibility.
 */

// Project converter — ExportProject construction
export {
  type BuildExportProjectOptions,
  buildExportProjectFromProject,
  buildExportTimeline,
  buildExportClipKeyframes,
} from './ffmpeg-builder/project-converter';

// Settings normalization — export settings, presets, normalization
export {
  DEFAULT_EXPORT_SETTINGS,
  SETPTS_EXPRESSION_LIMIT,
  GIF_PALETTE_PLACEHOLDER,
  LOUDNORM_MEASURED_I_PLACEHOLDER,
  LOUDNORM_MEASURED_TP_PLACEHOLDER,
  LOUDNORM_MEASURED_LRA_PLACEHOLDER,
  LOUDNORM_MEASURED_THRESH_PLACEHOLDER,
  LOUDNORM_OFFSET_PLACEHOLDER,
  WATERMARK_MARGIN_PX,
  SLATE_DURATION_SECONDS,
  CUSTOM_SHADER_SEQUENCE_KIND,
  PATH_TEXT_SEQUENCE_KIND,
  MOTION_GRAPHIC_SEQUENCE_PATH_MODE,
  EXPORT_PREVIEW_SAMPLE_KINDS,
  type LoudnessNormalizationPreset,
  type BuildFfmpegExportPlanOptions,
  type SubtitleLanguageGroup,
  DEFAULT_EXPORT_MASTER_EQ_BANDS,
  DEFAULT_EXPORT_MASTER_PROCESSING,
  normalizeLoudnessNormalization,
  normalizeVideoProfile,
  normalizeExportAudioVisualization,
  normalizeAudioVisualizationBackground,
  normalizeExportReframeSettings,
  normalizeExportSpatialAudioAssets,
  mergeExportMetadata,
  normalizeExportMasterProcessing,
  hasExportMasterProcessing,
  normalizeExportMasterEq,
  normalizeExportMasterEqBand,
  normalizeSettingsForExportFormat,
  constrainDimensions,
  normalizeExportWatermark,
  normalizeWatermarkPosition,
  normalizeTimecodeBurnIn,
  normalizeExportSlate,
  buildTimecodeBurnInFilter,
  buildSlateVideoFilters,
  buildWatermarkFilters,
  buildWatermarkExpression,
  calculateWatermarkOverlayPosition,
  finiteNumber,
  buildGifExportPasses,
  buildExportRangeOutputArgs,
  buildLoudnessNormalizationPasses,
  buildFfmpegFullArgs,
  normalizeHexColor,
  parseHexColor,
} from './ffmpeg-builder/settings-normalize';

// Core export plan — orchestrator
export {
  buildFfmpegExportPlan,
  buildFfmpegCurrentFrameExportPlan,
  type StemExportPlan,
  buildStemExportPlans,
  calculateExportPreviewSampleTimes,
  buildFfmpegPreviewSamplePlans,
  buildNestedSequencePlans,
} from './ffmpeg-builder/export-plan';

// Visual filters — compositing, transitions, color, masks, effects
export {
  type VisualItem,
  buildVisualItems,
  buildPlaybackStartByClipId,
  findExportTransitionPair,
  buildTransitionClipFilter,
  isTransitionVisualClip,
  areExportClipsAdjacent,
  clampExportTransitionDuration,
  buildSmartTransitionFilters,
  mapTransitionType,
  buildShapeWipeGeqExpression,
  type TransitionPreviewArgsOptions,
  buildTransitionPreviewArgs,
  visualKindOrder,
  buildMediaCompositeFilter,
  buildAdjustmentLayerFilters,
  buildVisualClipFilter,
  buildColorNodeGraphVisualFilter,
  buildColorGradingGraphVisualFilter,
  buildVisualPreColorFilters,
  buildVisualPostColorFilters,
  buildVisualPostKeyFilters,
  buildPanoramaProjectionFilters,
  hasSphericalVideoClips,
  buildDifferenceMatteClipFilter,
  buildPrivacyBlurClipFilter,
  buildPrivacyBlurMaskGraph,
  buildPrivacyBlurEffectFilter,
  buildMaskTimelineExpression,
  hasPrivacyBlurMasks,
  getPrivacyBlurMasks,
  isKenBurnsAnimatedScaleClip,
  buildReframeFilters,
  buildChromaKeyFilters,
  isDifferenceMatteEnabled,
  formatChromaKeyColor,
  buildStabilizationFilters,
  buildSlowMotionFilters,
  buildFrameInterpolationFilters,
  buildFrameInterpolationFilterArg,
  buildVideoRestorationFilters,
  buildQualityEnhancementFilters,
  getMinimumClipSpeed,
  buildMaskFilters,
  buildClipBorderFilters,
  isSimpleRectMask,
  buildSimpleRectMaskFilter,
  buildGeqMaskFilter,
  buildRectMaskExpression,
  buildEllipseMaskExpression,
  buildPathMaskExpression,
  getPathVertex,
  buildPathTriangleExpression,
  buildPathEdgeExpression,
  triangleArea,
  buildSetptsFilter,
  buildStaticSetptsFilter,
  buildSpeedRampSetptsExpression,
  buildSpeedRampSegments,
  getAverageClipSpeed,
  buildScaleFilter,
  buildKenBurnsZoompanFilter,
  buildOpacityFilters,
  buildOverlayXExpression,
  buildOverlayYExpression,
  buildColorCorrectionFilters,
  buildThreeWayColorFilter,
  colorBalanceValue,
  buildEffectFilters,
  buildColorGradingFilters,
  buildWindowMaskFfmpegFilter,
} from './ffmpeg-builder/visual-filters';

// Audio visualization — spectrum, waveform, theme decorations
export {
  type AudioSpectrumExportItem,
  collectAudioSpectrumEffects,
  buildAudioSpectrumFilter,
  buildAudioSpectrumOverlayYExpression,
  buildAudioVisualizationBackgroundFilters,
  buildAudioVisualizationFilter,
  type AudioSpectrumVisualFilterInput,
  buildAudioSpectrumVisualFilter,
  hasAudioVisualizationThemeDecorations,
  appendAudioVisualizationThemeDecorationFilters,
  buildAudioSpectrumGradientFilters,
  buildColorChannelMixerForHex,
  buildCircularAlphaMaskFilter,
  buildAudioVisualizationOverlayPosition,
  buildGradientChannelExpression,
} from './ffmpeg-builder/audio-visualization';

// Text and subtitle filters — drawtext, credits, subtitles
export {
  buildInputArgs,
  buildCustomShaderSequenceInputArgs,
  buildCustomShaderSequenceClip,
  buildPathTextSequenceArtifact,
  buildMotionGraphicSequenceArtifact,
  buildCustomShaderSequenceArtifact,
  buildImageSequenceArtifact,
  pngSequenceOutputPath,
  escapeConcatPath,
  formatSequenceFrameDuration,
  getExportClipSourceDuration,
  buildTextFilter,
  buildAdvancedTextFilter,
  shouldUseAdvancedTextFilters,
  buildOpenTypeDrawtextOptions,
  exportTextStyleToTextStyle,
  resolveAudioVisualizationBackground,
  buildCreditsRollFilter,
  buildPathTextSequenceOverlayFilter,
  buildTextFontSizeExpression,
  buildDrawtextPositionExpression,
  buildSubtitleBurnInFilter,
  type SubtitleArtifactOptions,
  buildSubtitleArtifact,
  buildSubtitleLanguageGroups,
  selectSubtitleBurnInGroup,
  subtitleLanguageToFfmpegMetadata,
  buildSubtitleCueInputs,
  buildSubtitleCueInput,
  projectFrameRateFromClip,
  serializeSubtitleCueInputs,
  buildSubtitleInputArgs,
  buildSoftSubtitleCodec,
  normalizeSubtitleFormat,
} from './ffmpeg-builder/text-subtitle-filters';

// Audio filters — master, track, per-clip audio processing
export {
  buildAudioEffectChainFilters,
  buildMixerChannelAudioFilters,
  buildAudioFilters,
  buildAtempoFilters,
  buildPitchAndReverseAudioFilters,
  getLoudnessNormalizationPreset,
  buildLoudnormAnalysisFilter,
  buildLoudnormRenderFilter,
  buildAudioDenoiseFilters,
  buildAudioRestorationFilters,
  buildPanFilter,
  buildAutomationFilters,
  buildSpatialAudioFilter,
  escapeSofalizerArg,
  escapeFilterFileValue,
  buildSpatialPanGainExpression,
  buildSpatialVolumeExpression,
  buildAudioChannelRoutingFilter,
  buildTrackAudioFilters,
  buildMasterAudioFilters,
  buildEqualizerFilters,
  buildAudioFadeFilters,
  formatAudioFadeCurve,
  buildVolumeFilter,
} from './ffmpeg-builder/audio-filters';

// Utilities — formatting, encoding args, hardware encoder
export {
  buildBitrateArgs,
  buildVideoEncodingArgs,
  buildVideoProfileArgs,
  buildContainerArgs,
  buildExportColorMetadataArgs,
  buildExportContainerMetadataArgs,
  buildExportColorManagementFilters,
  shouldGenerateIccProfile,
  buildSourceColorSpaceConversionFilters,
  type AnimatedProperty,
  getAnimatedFrames,
  buildLocalExpression,
  buildTimelineExpression,
  buildSegmentExpression,
  buildEasingExpression,
  buildBounceEasingExpression,
  formatAtempo,
  formatPitchRatio,
  formatFfmpegNumber,
  safeLabel,
  nestedInputPlaceholder,
  formatScale,
  formatOpacity,
  formatVolume,
  formatPan,
  formatCompressorLinear,
  formatSigned,
  formatOffsetExpression,
  cssColorToAssColor,
  buildHardwareEncoderArgs,
} from './ffmpeg-builder/utils';
