/**
 * LLM Orchestrator
 *
 * Manages communication between local editor and remote LLM providers.
 * Implements the "local feature extraction + cloud reasoning" pattern.
 *
 * Pipeline:
 * 1. Receives MaterialMetadata from local semantic extractor
 * 2. Builds structured prompts with privacy-safe data only
 * 3. Sends to LLM provider (OpenAI/Claude compatible)
 * 4. Parses structured JSON editing instructions from response
 * 5. Validates and returns executable EditInstruction[]
 *
 * Privacy: Only sends text metadata + optional compressed low-res previews.
 * Raw video/audio streams are NEVER included.
 */
import type { MaterialMetadata } from './semantic-extractor';
import type { AIProvider } from '../ai-service';
/** Supported LLM action types */
export type EditActionType = 'cut' | 'trim' | 'reorder' | 'add_transition' | 'add_subtitle' | 'adjust_audio' | 'add_effect' | 'split' | 'merge' | 'speed' | 'fade' | 'narration';
/** Single editing instruction from LLM */
export interface EditInstruction {
    /** Unique instruction ID */
    id: string;
    /** Action type */
    action: EditActionType;
    /** Target clip index or time range */
    target: {
        /** Source material index (in the analyzed set) */
        materialIndex?: number;
        /** Start time in seconds */
        startSec?: number;
        /** End time in seconds */
        endSec?: number;
        /** Target track index */
        trackIndex?: number;
    };
    /** Action-specific parameters */
    params: Record<string, unknown>;
    /** LLM confidence 0-1 */
    confidence: number;
    /** Human-readable reason */
    reason: string;
}
/** Editing plan generated by LLM */
export interface EditPlan {
    /** Plan title */
    title: string;
    /** Plan description */
    description: string;
    /** Ordered list of editing instructions */
    instructions: EditInstruction[];
    /** Estimated final duration in seconds */
    estimatedDurationSec: number;
    /** LLM-generated creative notes */
    creativeNotes?: string;
}
/** Platform-specific content metadata */
export interface PlatformContent {
    platform: string;
    title: string;
    description: string;
    tags: string[];
    thumbnail?: {
        timeSec: number;
        reason: string;
    };
    hashtags?: string[];
    category?: string;
    language?: string;
}
/** LLM conversation message */
export interface LLMMessage {
    role: 'system' | 'user' | 'assistant';
    content: string;
    /** Optional low-res image attachments */
    images?: Array<{
        base64: string;
        mimeType: 'image/jpeg' | 'image/png';
        description?: string;
    }>;
}
/** LLM request configuration */
export interface LLMRequestConfig {
    /** Provider to use */
    provider: AIProvider;
    /** Model override (uses provider default if omitted) */
    model?: string;
    /** Max tokens for response */
    maxTokens?: number;
    /** Temperature 0-1 */
    temperature?: number;
    /** Response format hint */
    responseFormat?: 'json' | 'text';
}
/** LLM response */
export interface LLMResponse {
    /** Response content */
    content: string;
    /** Parsed JSON (if responseFormat was 'json') */
    parsed?: unknown;
    /** Token usage */
    usage: {
        inputTokens: number;
        outputTokens: number;
    };
    /** Latency in ms */
    latencyMs: number;
    /** Provider used */
    providerId: string;
}
/**
 * Build an editing prompt from material metadata.
 * Strips any raw media data, includes only text and optional low-res previews.
 */
export declare function buildEditingPrompt(materials: MaterialMetadata[], userRequest: string): LLMMessage[];
/**
 * Build a platform content generation prompt.
 */
export declare function buildPlatformPrompt(metadata: MaterialMetadata, platforms: string[], userHints?: string): LLMMessage[];
/**
 * Build a conversational editing prompt.
 * For the "AI dialogue editing" panel where user iterates with LLM.
 */
export declare function buildConversationalPrompt(materials: MaterialMetadata[], conversationHistory: LLMMessage[], userMessage: string): LLMMessage[];
/** Parse error details */
export interface ParseError {
    field: string;
    message: string;
    raw?: unknown;
}
/** Result of parsing LLM response */
export type ParseResult<T> = {
    ok: true;
    data: T;
} | {
    ok: false;
    errors: ParseError[];
};
/**
 * Safely parse an EditPlan from LLM JSON response.
 * Validates structure and instruction actions.
 */
export declare function parseEditPlan(jsonStr: string): ParseResult<EditPlan>;
/**
 * Parse platform content from LLM JSON response.
 */
export declare function parsePlatformContent(jsonStr: string): ParseResult<PlatformContent[]>;
/** Execution result for a single instruction */
export interface InstructionExecutionResult {
    instructionId: string;
    success: boolean;
    /** Applied changes description */
    changes?: string;
    /** Error message if failed */
    error?: string;
    /** Execution time in ms */
    executionMs: number;
}
/** Full plan execution result */
export interface PlanExecutionResult {
    planTitle: string;
    totalInstructions: number;
    executed: number;
    succeeded: number;
    failed: number;
    skipped: number;
    results: InstructionExecutionResult[];
    totalMs: number;
}
/**
 * Validate that an instruction's target references are within bounds.
 */
export declare function validateInstructionTarget(instruction: EditInstruction, materialCount: number, maxDurationSec: number): {
    valid: boolean;
    error?: string;
};
/**
 * Sort instructions by execution priority.
 * Some actions must run before others (e.g., cut before reorder).
 */
export declare function sortInstructionsByPriority(instructions: EditInstruction[]): EditInstruction[];
/** Abstract LLM provider interface for testability */
export interface LLMProviderAdapter {
    /** Send messages and get response */
    chat(messages: LLMMessage[], config: LLMRequestConfig): Promise<LLMResponse>;
}
/**
 * Build headers for LLM API call.
 */
export declare function buildLLMHeaders(provider: AIProvider): Record<string, string>;
/**
 * Build the request body for OpenAI-compatible API.
 */
export declare function buildOpenAIRequestBody(messages: LLMMessage[], config: LLMRequestConfig): Record<string, unknown>;
export interface OrchestratorConfig {
    /** LLM provider adapter */
    adapter: LLMProviderAdapter;
    /** Provider info */
    provider: AIProvider;
    /** Model override */
    model?: string;
    /** Max retries on parse failure */
    maxRetries?: number;
    /** Filter instructions below this confidence */
    confidenceThreshold?: number;
}
/**
 * Generate an editing plan from materials and user request.
 */
export declare function generateEditPlan(materials: MaterialMetadata[], userRequest: string, config: OrchestratorConfig): Promise<{
    plan: EditPlan | null;
    response: LLMResponse;
    parseErrors?: ParseError[];
}>;
/**
 * Generate platform-specific content for video publishing.
 */
export declare function generatePlatformContent(metadata: MaterialMetadata, platforms: string[], config: OrchestratorConfig, userHints?: string): Promise<{
    contents: PlatformContent[] | null;
    response: LLMResponse;
    parseErrors?: ParseError[];
}>;
//# sourceMappingURL=llm-orchestrator.d.ts.map