/**
 * LLM Orchestrator
 *
 * Manages communication between local editor and remote LLM providers.
 * Implements the "local feature extraction + cloud reasoning" pattern.
 *
 * Pipeline:
 * 1. Receives MaterialMetadata from local semantic extractor
 * 2. Builds structured prompts with privacy-safe data only
 * 3. Sends to LLM provider (OpenAI/Claude compatible)
 * 4. Parses structured JSON editing instructions from response
 * 5. Validates and returns executable EditInstruction[]
 *
 * Privacy: Only sends text metadata + optional compressed low-res previews.
 * Raw video/audio streams are NEVER included.
 */

import type { MaterialMetadata, KeyFrame } from './semantic-extractor';
import type { AIProvider } from '../ai-service';

// ─── LLM Instruction Protocol ──────────────────────────────────

/** Supported LLM action types */
export type EditActionType =
  | 'cut'          // Remove a segment
  | 'trim'         // Trim start/end of a clip
  | 'reorder'      // Change clip order
  | 'add_transition'  // Add transition between clips
  | 'add_subtitle'    // Add subtitle overlay
  | 'adjust_audio'    // Adjust audio levels
  | 'add_effect'      // Apply visual effect
  | 'split'           // Split clip at timepoint
  | 'merge'           // Merge adjacent clips
  | 'speed'           // Change playback speed
  | 'fade'            // Add fade in/out
  | 'narration';      // Add narration track

/** Single editing instruction from LLM */
export interface EditInstruction {
  /** Unique instruction ID */
  id: string;
  /** Action type */
  action: EditActionType;
  /** Target clip index or time range */
  target: {
    /** Source material index (in the analyzed set) */
    materialIndex?: number;
    /** Start time in seconds */
    startSec?: number;
    /** End time in seconds */
    endSec?: number;
    /** Target track index */
    trackIndex?: number;
  };
  /** Action-specific parameters */
  params: Record<string, unknown>;
  /** LLM confidence 0-1 */
  confidence: number;
  /** Human-readable reason */
  reason: string;
}

/** Editing plan generated by LLM */
export interface EditPlan {
  /** Plan title */
  title: string;
  /** Plan description */
  description: string;
  /** Ordered list of editing instructions */
  instructions: EditInstruction[];
  /** Estimated final duration in seconds */
  estimatedDurationSec: number;
  /** LLM-generated creative notes */
  creativeNotes?: string;
}

/** Platform-specific content metadata */
export interface PlatformContent {
  platform: string;
  title: string;
  description: string;
  tags: string[];
  thumbnail?: {
    timeSec: number;
    reason: string;
  };
  hashtags?: string[];
  category?: string;
  language?: string;
}

/** LLM conversation message */
export interface LLMMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
  /** Optional low-res image attachments */
  images?: Array<{
    base64: string;
    mimeType: 'image/jpeg' | 'image/png';
    description?: string;
  }>;
}

/** LLM request configuration */
export interface LLMRequestConfig {
  /** Provider to use */
  provider: AIProvider;
  /** Model override (uses provider default if omitted) */
  model?: string;
  /** Max tokens for response */
  maxTokens?: number;
  /** Temperature 0-1 */
  temperature?: number;
  /** Response format hint */
  responseFormat?: 'json' | 'text';
}

/** LLM response */
export interface LLMResponse {
  /** Response content */
  content: string;
  /** Parsed JSON (if responseFormat was 'json') */
  parsed?: unknown;
  /** Token usage */
  usage: {
    inputTokens: number;
    outputTokens: number;
  };
  /** Latency in ms */
  latencyMs: number;
  /** Provider used */
  providerId: string;
}

// ─── Prompt Engineering ─────────────────────────────────────────

const SYSTEM_PROMPT_EDITING = `You are an expert video editor AI assistant. You analyze media metadata and generate structured editing instructions.

IMPORTANT RULES:
1. You receive ONLY structured metadata (JSON) and optional low-res preview images.
2. Raw video/audio is NEVER available to you.
3. All time references use seconds (floating point).
4. Output MUST be valid JSON matching the EditPlan schema.
5. Be conservative - prefer fewer, high-confidence edits over many speculative ones.
6. Always provide a reason for each instruction.

Output JSON schema:
{
  "title": "string - plan title",
  "description": "string - what this plan achieves",
  "instructions": [
    {
      "id": "string - unique id",
      "action": "cut|trim|reorder|add_transition|add_subtitle|adjust_audio|add_effect|split|merge|speed|fade|narration",
      "target": {
        "materialIndex": "number (optional)",
        "startSec": "number (optional)",
        "endSec": "number (optional)",
        "trackIndex": "number (optional)"
      },
      "params": { "action-specific parameters" },
      "confidence": "number 0-1",
      "reason": "string - why this edit"
    }
  ],
  "estimatedDurationSec": "number",
  "creativeNotes": "string (optional)"
}`;

const SYSTEM_PROMPT_PLATFORM = `You are a social media content optimization expert. You analyze video metadata and generate platform-specific content (titles, descriptions, tags).

IMPORTANT RULES:
1. Tailor content to each platform's audience and conventions.
2. Use the video's transcript and visual analysis for context.
3. Output MUST be valid JSON.
4. Be creative but accurate - don't invent content not supported by the metadata.

Output JSON schema:
{
  "platforms": [
    {
      "platform": "string - platform id",
      "title": "string",
      "description": "string",
      "tags": ["string"],
      "hashtags": ["string (optional)"],
      "category": "string (optional)",
      "thumbnail": { "timeSec": number, "reason": "string" }
    }
  ]
}`;

/**
 * Build an editing prompt from material metadata.
 * Strips any raw media data, includes only text and optional low-res previews.
 */
export function buildEditingPrompt(
  materials: MaterialMetadata[],
  userRequest: string
): LLMMessage[] {
  const systemMessage: LLMMessage = {
    role: 'system',
    content: SYSTEM_PROMPT_EDITING,
  };

  // Build compact material summary (strip large fields)
  const materialSummaries = materials.map((m, i) => ({
    index: i,
    fileName: m.source.fileName,
    duration: m.source.durationSec,
    resolution: `${m.source.width}x${m.source.height}`,
    fps: m.source.fps,
    tags: m.tags,
    transcript: m.transcriptText.substring(0, 2000), // Truncate long transcripts
    keyFrameCount: m.keyFrames.length,
    audioProfile: m.audioProfile,
    visualProfile: m.visualProfile,
    sceneDistribution: m.visualProfile.sceneDistribution,
  }));

  const userMessage: LLMMessage = {
    role: 'user',
    content: `## Available Materials\n\n${JSON.stringify(materialSummaries, null, 2)}\n\n## User Request\n\n${userRequest}\n\nPlease generate an editing plan in JSON format.`,
  };

  return [systemMessage, userMessage];
}

/**
 * Build a platform content generation prompt.
 */
export function buildPlatformPrompt(
  metadata: MaterialMetadata,
  platforms: string[],
  userHints?: string
): LLMMessage[] {
  const systemMessage: LLMMessage = {
    role: 'system',
    content: SYSTEM_PROMPT_PLATFORM,
  };

  const compactMeta = {
    fileName: metadata.source.fileName,
    duration: metadata.source.durationSec,
    tags: metadata.tags,
    transcript: metadata.transcriptText.substring(0, 3000),
    summary: metadata.summary,
    visualProfile: metadata.visualProfile,
    audioProfile: metadata.audioProfile,
  };

  const userMessage: LLMMessage = {
    role: 'user',
    content: `## Video Metadata\n\n${JSON.stringify(compactMeta, null, 2)}\n\n## Target Platforms\n\n${JSON.stringify(platforms)}\n\n${userHints ? `## Additional Hints\n\n${userHints}\n\n` : ''}Generate platform-optimized content in JSON format.`,
  };

  return [systemMessage, userMessage];
}

/**
 * Build a conversational editing prompt.
 * For the "AI dialogue editing" panel where user iterates with LLM.
 */
export function buildConversationalPrompt(
  materials: MaterialMetadata[],
  conversationHistory: LLMMessage[],
  userMessage: string
): LLMMessage[] {
  const systemMessage: LLMMessage = {
    role: 'system',
    content: SYSTEM_PROMPT_EDITING,
  };

  // Only include material summary once in the first user message or if history is empty
  const materialSummary = materials.map((m, i) => ({
    index: i,
    fileName: m.source.fileName,
    duration: m.source.durationSec,
    tags: m.tags,
    transcript: m.transcriptText.substring(0, 1000),
  }));

  const contextMessage: LLMMessage = {
    role: 'user',
    content: `Here are the available materials:\n\n${JSON.stringify(materialSummary, null, 2)}`,
  };

  return [
    systemMessage,
    contextMessage,
    ...conversationHistory,
    { role: 'user', content: userMessage },
  ];
}

// ─── Response Parsing ───────────────────────────────────────────

/** Parse error details */
export interface ParseError {
  field: string;
  message: string;
  raw?: unknown;
}

/** Result of parsing LLM response */
export type ParseResult<T> =
  | { ok: true; data: T }
  | { ok: false; errors: ParseError[] };

/**
 * Safely parse an EditPlan from LLM JSON response.
 * Validates structure and instruction actions.
 */
export function parseEditPlan(jsonStr: string): ParseResult<EditPlan> {
  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonStr);
  } catch {
    return { ok: false, errors: [{ field: 'root', message: 'Invalid JSON' }] };
  }

  if (typeof parsed !== 'object' || parsed === null) {
    return { ok: false, errors: [{ field: 'root', message: 'Expected object' }] };
  }

  const obj = parsed as Record<string, unknown>;
  const errors: ParseError[] = [];

  if (typeof obj.title !== 'string') {
    errors.push({ field: 'title', message: 'Expected string' });
  }
  if (typeof obj.description !== 'string') {
    errors.push({ field: 'description', message: 'Expected string' });
  }
  if (!Array.isArray(obj.instructions)) {
    errors.push({ field: 'instructions', message: 'Expected array' });
  } else {
    const validActions: EditActionType[] = [
      'cut', 'trim', 'reorder', 'add_transition', 'add_subtitle',
      'adjust_audio', 'add_effect', 'split', 'merge', 'speed', 'fade', 'narration',
    ];

    for (let i = 0; i < obj.instructions.length; i++) {
      const inst = obj.instructions[i] as Record<string, unknown>;
      if (typeof inst.id !== 'string') {
        errors.push({ field: `instructions[${i}].id`, message: 'Expected string' });
      }
      if (!validActions.includes(inst.action as EditActionType)) {
        errors.push({ field: `instructions[${i}].action`, message: `Invalid action: ${inst.action}` });
      }
      if (typeof inst.confidence !== 'number' || inst.confidence < 0 || inst.confidence > 1) {
        errors.push({ field: `instructions[${i}].confidence`, message: 'Expected number 0-1' });
      }
      if (typeof inst.reason !== 'string') {
        errors.push({ field: `instructions[${i}].reason`, message: 'Expected string' });
      }
    }
  }

  if (typeof obj.estimatedDurationSec !== 'number') {
    errors.push({ field: 'estimatedDurationSec', message: 'Expected number' });
  }

  if (errors.length > 0) {
    return { ok: false, errors };
  }

  return {
    ok: true,
    data: {
      title: obj.title as string,
      description: obj.description as string,
      instructions: obj.instructions as EditInstruction[],
      estimatedDurationSec: obj.estimatedDurationSec as number,
      creativeNotes: obj.creativeNotes as string | undefined,
    },
  };
}

/**
 * Parse platform content from LLM JSON response.
 */
export function parsePlatformContent(jsonStr: string): ParseResult<PlatformContent[]> {
  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonStr);
  } catch {
    return { ok: false, errors: [{ field: 'root', message: 'Invalid JSON' }] };
  }

  if (typeof parsed !== 'object' || parsed === null) {
    return { ok: false, errors: [{ field: 'root', message: 'Expected object' }] };
  }

  const obj = parsed as Record<string, unknown>;
  if (!Array.isArray(obj.platforms)) {
    return { ok: false, errors: [{ field: 'platforms', message: 'Expected array' }] };
  }

  const errors: ParseError[] = [];
  for (let i = 0; i < obj.platforms.length; i++) {
    const p = obj.platforms[i] as Record<string, unknown>;
    if (typeof p.platform !== 'string') {
      errors.push({ field: `platforms[${i}].platform`, message: 'Expected string' });
    }
    if (typeof p.title !== 'string') {
      errors.push({ field: `platforms[${i}].title`, message: 'Expected string' });
    }
    if (typeof p.description !== 'string') {
      errors.push({ field: `platforms[${i}].description`, message: 'Expected string' });
    }
    if (!Array.isArray(p.tags)) {
      errors.push({ field: `platforms[${i}].tags`, message: 'Expected array' });
    }
  }

  if (errors.length > 0) return { ok: false, errors };
  return { ok: true, data: obj.platforms as PlatformContent[] };
}

// ─── Instruction Executor ───────────────────────────────────────

/** Execution result for a single instruction */
export interface InstructionExecutionResult {
  instructionId: string;
  success: boolean;
  /** Applied changes description */
  changes?: string;
  /** Error message if failed */
  error?: string;
  /** Execution time in ms */
  executionMs: number;
}

/** Full plan execution result */
export interface PlanExecutionResult {
  planTitle: string;
  totalInstructions: number;
  executed: number;
  succeeded: number;
  failed: number;
  skipped: number;
  results: InstructionExecutionResult[];
  totalMs: number;
}

/**
 * Validate that an instruction's target references are within bounds.
 */
export function validateInstructionTarget(
  instruction: EditInstruction,
  materialCount: number,
  maxDurationSec: number
): { valid: boolean; error?: string } {
  const { target } = instruction;

  if (target.materialIndex !== undefined) {
    if (target.materialIndex < 0 || target.materialIndex >= materialCount) {
      return { valid: false, error: `materialIndex ${target.materialIndex} out of range [0, ${materialCount - 1}]` };
    }
  }

  if (target.startSec !== undefined && target.startSec < 0) {
    return { valid: false, error: `startSec ${target.startSec} is negative` };
  }

  if (target.endSec !== undefined && target.endSec > maxDurationSec) {
    return { valid: false, error: `endSec ${target.endSec} exceeds max duration ${maxDurationSec}` };
  }

  if (target.startSec !== undefined && target.endSec !== undefined && target.startSec >= target.endSec) {
    return { valid: false, error: 'startSec must be less than endSec' };
  }

  return { valid: true };
}

/**
 * Sort instructions by execution priority.
 * Some actions must run before others (e.g., cut before reorder).
 */
export function sortInstructionsByPriority(instructions: EditInstruction[]): EditInstruction[] {
  const priority: Record<EditActionType, number> = {
    split: 0,
    cut: 1,
    trim: 2,
    merge: 3,
    reorder: 4,
    speed: 5,
    fade: 6,
    add_transition: 7,
    add_effect: 8,
    adjust_audio: 9,
    add_subtitle: 10,
    narration: 11,
  };

  return [...instructions].sort((a, b) => {
    const pa = priority[a.action] ?? 99;
    const pb = priority[b.action] ?? 99;
    return pa - pb;
  });
}

// ─── LLM Provider Interface ────────────────────────────────────

/** Abstract LLM provider interface for testability */
export interface LLMProviderAdapter {
  /** Send messages and get response */
  chat(messages: LLMMessage[], config: LLMRequestConfig): Promise<LLMResponse>;
}

/**
 * Build headers for LLM API call.
 */
export function buildLLMHeaders(provider: AIProvider): Record<string, string> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };

  if (provider.apiKey) {
    headers['Authorization'] = `Bearer ${provider.apiKey}`;
  }

  if (provider.customHeaders) {
    Object.assign(headers, provider.customHeaders);
  }

  return headers;
}

/**
 * Build the request body for OpenAI-compatible API.
 */
export function buildOpenAIRequestBody(
  messages: LLMMessage[],
  config: LLMRequestConfig
): Record<string, unknown> {
  const openaiMessages = messages.map(msg => {
    const parts: Array<{ type: string; text?: string; image_url?: { url: string } }> = [];

    parts.push({ type: 'text', text: msg.content });

    if (msg.images) {
      for (const img of msg.images) {
        parts.push({
          type: 'image_url',
          image_url: { url: `data:${img.mimeType};base64,${img.base64}` },
        });
      }
    }

    return {
      role: msg.role,
      content: parts.length === 1 && parts[0].type === 'text' ? msg.content : parts,
    };
  });

  return {
    model: config.model ?? config.provider.defaultModel,
    messages: openaiMessages,
    max_tokens: config.maxTokens ?? 4096,
    temperature: config.temperature ?? 0.7,
    ...(config.responseFormat === 'json' ? { response_format: { type: 'json_object' } } : {}),
  };
}

// ─── Orchestrator ───────────────────────────────────────────────

export interface OrchestratorConfig {
  /** LLM provider adapter */
  adapter: LLMProviderAdapter;
  /** Provider info */
  provider: AIProvider;
  /** Model override */
  model?: string;
  /** Max retries on parse failure */
  maxRetries?: number;
  /** Filter instructions below this confidence */
  confidenceThreshold?: number;
}

const DEFAULT_CONFIDENCE_THRESHOLD = 0.6;

/**
 * Generate an editing plan from materials and user request.
 */
export async function generateEditPlan(
  materials: MaterialMetadata[],
  userRequest: string,
  config: OrchestratorConfig
): Promise<{ plan: EditPlan | null; response: LLMResponse; parseErrors?: ParseError[] }> {
  const messages = buildEditingPrompt(materials, userRequest);
  const requestConfig: LLMRequestConfig = {
    provider: config.provider,
    model: config.model,
    responseFormat: 'json',
    temperature: 0.7,
  };

  const maxRetries = config.maxRetries ?? 2;
  let lastResponse: LLMResponse | null = null;
  let lastErrors: ParseError[] | undefined;

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    const response = await config.adapter.chat(messages, requestConfig);
    lastResponse = response;

    const result = parseEditPlan(response.content);
    if (result.ok) {
      // Filter by confidence
      const threshold = config.confidenceThreshold ?? DEFAULT_CONFIDENCE_THRESHOLD;
      const filtered = {
        ...result.data,
        instructions: result.data.instructions.filter(i => i.confidence >= threshold),
      };
      return { plan: filtered, response };
    }

    lastErrors = result.errors;
  }

  return { plan: null, response: lastResponse!, parseErrors: lastErrors };
}

/**
 * Generate platform-specific content for video publishing.
 */
export async function generatePlatformContent(
  metadata: MaterialMetadata,
  platforms: string[],
  config: OrchestratorConfig,
  userHints?: string
): Promise<{ contents: PlatformContent[] | null; response: LLMResponse; parseErrors?: ParseError[] }> {
  const messages = buildPlatformPrompt(metadata, platforms, userHints);
  const requestConfig: LLMRequestConfig = {
    provider: config.provider,
    model: config.model,
    responseFormat: 'json',
    temperature: 0.8,
  };

  const response = await config.adapter.chat(messages, requestConfig);
  const result = parsePlatformContent(response.content);

  if (result.ok) {
    return { contents: result.data, response };
  }

  return { contents: null, response, parseErrors: result.errors };
}
